/* adapter.c generated by valac 0.32.1, the Vala compiler
 * generated from adapter.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <gee.h>


#define RUBRIC_ORM_TYPE_ADAPTER (rubric_orm_adapter_get_type ())
#define RUBRIC_ORM_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_ADAPTER, RubricORMAdapter))
#define RUBRIC_ORM_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_ADAPTER))
#define RUBRIC_ORM_ADAPTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_ADAPTER, RubricORMAdapterIface))

typedef struct _RubricORMAdapter RubricORMAdapter;
typedef struct _RubricORMAdapterIface RubricORMAdapterIface;

#define RUBRIC_ORM_TYPE_COMMAND_BUILDER (rubric_orm_command_builder_get_type ())
#define RUBRIC_ORM_COMMAND_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER, RubricORMCommandBuilder))
#define RUBRIC_ORM_IS_COMMAND_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER))
#define RUBRIC_ORM_COMMAND_BUILDER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER, RubricORMCommandBuilderIface))

typedef struct _RubricORMCommandBuilder RubricORMCommandBuilder;
typedef struct _RubricORMCommandBuilderIface RubricORMCommandBuilderIface;

#define RUBRIC_ORM_TYPE_COMMAND (rubric_orm_command_get_type ())
#define RUBRIC_ORM_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommand))
#define RUBRIC_ORM_IS_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_COMMAND))
#define RUBRIC_ORM_COMMAND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommandIface))

typedef struct _RubricORMCommand RubricORMCommand;
typedef struct _RubricORMCommandIface RubricORMCommandIface;

#define RUBRIC_ORM_TYPE_CURSOR (rubric_orm_cursor_get_type ())
#define RUBRIC_ORM_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursor))
#define RUBRIC_ORM_IS_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_CURSOR))
#define RUBRIC_ORM_CURSOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursorIface))

typedef struct _RubricORMCursor RubricORMCursor;
typedef struct _RubricORMCursorIface RubricORMCursorIface;

#define RUBRIC_ORM_TYPE_RESOURCE (rubric_orm_resource_get_type ())
#define RUBRIC_ORM_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResource))
#define RUBRIC_ORM_IS_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_RESOURCE))
#define RUBRIC_ORM_RESOURCE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResourceIface))

typedef struct _RubricORMResource RubricORMResource;
typedef struct _RubricORMResourceIface RubricORMResourceIface;

typedef enum  {
	RUBRIC_ORM_ERROR_ADAPTER_OPEN,
	RUBRIC_ORM_ERROR_COMMAND_NO_SQL,
	RUBRIC_ORM_ERROR_COMMAND_DRIVER,
	RUBRIC_ORM_ERROR_REPOSITORY_EMPTY_RESULT,
	RUBRIC_ORM_ERROR_RESOURCE_CURSOR,
	RUBRIC_ORM_ERROR_COMMAND_NO_REPOSITORY
} RubricORMError;
#define RUBRIC_ORM_ERROR rubric_orm_error_quark ()
struct _RubricORMCursorIface {
	GTypeInterface parent_iface;
	void (*get_column) (RubricORMCursor* self, guint column, GValue* value);
	gboolean (*get_column_boolean) (RubricORMCursor* self, guint column);
	gdouble (*get_column_double) (RubricORMCursor* self, guint column);
	gfloat (*get_column_float) (RubricORMCursor* self, guint column);
	gint (*get_column_int) (RubricORMCursor* self, guint column);
	gint64 (*get_column_int64) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_name) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_string) (RubricORMCursor* self, guint column);
	guint (*get_column_uint) (RubricORMCursor* self, guint column);
	guint64 (*get_column_uint64) (RubricORMCursor* self, guint column);
	guint (*get_n_columns) (RubricORMCursor* self);
	gboolean (*next) (RubricORMCursor* self);
};

struct _RubricORMCommandIface {
	GTypeInterface parent_iface;
	gboolean (*execute) (RubricORMCommand* self, RubricORMCursor** cursor, GError** error);
};

struct _RubricORMResourceIface {
	GTypeInterface parent_iface;
};

struct _RubricORMCommandBuilderIface {
	GTypeInterface parent_iface;
	RubricORMCommand* (*build_count) (RubricORMCommandBuilder* self);
	GeeList* (*build_create) (RubricORMCommandBuilder* self, guint version);
	RubricORMCommand* (*build_delete) (RubricORMCommandBuilder* self);
	RubricORMCommand* (*build_insert) (RubricORMCommandBuilder* self, RubricORMResource* resource);
	RubricORMCommand* (*build_select) (RubricORMCommandBuilder* self);
	RubricORMCommand* (*build_update) (RubricORMCommandBuilder* self, RubricORMResource* resource);
};

struct _RubricORMAdapterIface {
	GTypeInterface parent_iface;
	gboolean (*execute_sql) (RubricORMAdapter* self, const gchar* sql, GError** error);
	void (*open_async) (RubricORMAdapter* self, const gchar* uri, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*open_finish) (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
	gboolean (*open) (RubricORMAdapter* self, const gchar* uri, GError** error);
	gboolean (*close) (RubricORMAdapter* self, GError** error);
	void (*close_async) (RubricORMAdapter* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*close_finish) (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
	void* (*get_handle) (RubricORMAdapter* self);
	RubricORMCommandBuilder* (*get_command_builder) (RubricORMAdapter* self, GParameter* parameters, int parameters_length1);
};

typedef void (*RubricORMAdapterCallback) (RubricORMAdapter* adapter, void* user_data);


GQuark rubric_orm_error_quark (void);
GType rubric_orm_cursor_get_type (void) G_GNUC_CONST;
GType rubric_orm_command_get_type (void) G_GNUC_CONST;
GType rubric_orm_resource_get_type (void) G_GNUC_CONST;
GType rubric_orm_command_builder_get_type (void) G_GNUC_CONST;
GType rubric_orm_adapter_get_type (void) G_GNUC_CONST;
gboolean rubric_orm_adapter_execute_sql (RubricORMAdapter* self, const gchar* sql, GError** error);
void rubric_orm_adapter_open_async (RubricORMAdapter* self, const gchar* uri, GAsyncReadyCallback _callback_, gpointer _user_data_);
gboolean rubric_orm_adapter_open_finish (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
gboolean rubric_orm_adapter_open (RubricORMAdapter* self, const gchar* uri, GError** error);
gboolean rubric_orm_adapter_close (RubricORMAdapter* self, GError** error);
void rubric_orm_adapter_close_async (RubricORMAdapter* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
gboolean rubric_orm_adapter_close_finish (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
void* rubric_orm_adapter_get_handle (RubricORMAdapter* self);
RubricORMCommandBuilder* rubric_orm_adapter_get_command_builder (RubricORMAdapter* self, GParameter* parameters, int parameters_length1);


gboolean rubric_orm_adapter_execute_sql (RubricORMAdapter* self, const gchar* sql, GError** error) {
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->execute_sql (self, sql, error);
#line 159 "adapter.c"
}


void rubric_orm_adapter_open_async (RubricORMAdapter* self, const gchar* uri, GAsyncReadyCallback _callback_, gpointer _user_data_) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->open_async (self, uri, _callback_, _user_data_);
#line 166 "adapter.c"
}


gboolean rubric_orm_adapter_open_finish (RubricORMAdapter* self, GAsyncResult* _res_, GError** error) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->open_finish (self, _res_, error);
#line 173 "adapter.c"
}


gboolean rubric_orm_adapter_open (RubricORMAdapter* self, const gchar* uri, GError** error) {
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->open (self, uri, error);
#line 182 "adapter.c"
}


gboolean rubric_orm_adapter_close (RubricORMAdapter* self, GError** error) {
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->close (self, error);
#line 191 "adapter.c"
}


void rubric_orm_adapter_close_async (RubricORMAdapter* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->close_async (self, _callback_, _user_data_);
#line 198 "adapter.c"
}


gboolean rubric_orm_adapter_close_finish (RubricORMAdapter* self, GAsyncResult* _res_, GError** error) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->close_finish (self, _res_, error);
#line 205 "adapter.c"
}


void* rubric_orm_adapter_get_handle (RubricORMAdapter* self) {
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->get_handle (self);
#line 214 "adapter.c"
}


RubricORMCommandBuilder* rubric_orm_adapter_get_command_builder (RubricORMAdapter* self, GParameter* parameters, int parameters_length1) {
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	return RUBRIC_ORM_ADAPTER_GET_INTERFACE (self)->get_command_builder (self, parameters, parameters_length1);
#line 223 "adapter.c"
}


static void rubric_orm_adapter_base_init (RubricORMAdapterIface * iface) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	static gboolean initialized = FALSE;
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
	if (!initialized) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/adapter.vala"
		initialized = TRUE;
#line 234 "adapter.c"
	}
}


GType rubric_orm_adapter_get_type (void) {
	static volatile gsize rubric_orm_adapter_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_adapter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMAdapterIface), (GBaseInitFunc) rubric_orm_adapter_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_adapter_type_id;
		rubric_orm_adapter_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMAdapter", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_adapter_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_adapter_type_id__volatile, rubric_orm_adapter_type_id);
	}
	return rubric_orm_adapter_type_id__volatile;
}



