/* command.c generated by valac 0.32.1, the Vala compiler
 * generated from command.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define RUBRIC_ORM_TYPE_COMMAND (rubric_orm_command_get_type ())
#define RUBRIC_ORM_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommand))
#define RUBRIC_ORM_IS_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_COMMAND))
#define RUBRIC_ORM_COMMAND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommandIface))

typedef struct _RubricORMCommand RubricORMCommand;
typedef struct _RubricORMCommandIface RubricORMCommandIface;

#define RUBRIC_ORM_TYPE_CURSOR (rubric_orm_cursor_get_type ())
#define RUBRIC_ORM_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursor))
#define RUBRIC_ORM_IS_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_CURSOR))
#define RUBRIC_ORM_CURSOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursorIface))

typedef struct _RubricORMCursor RubricORMCursor;
typedef struct _RubricORMCursorIface RubricORMCursorIface;

struct _RubricORMCursorIface {
	GTypeInterface parent_iface;
	void (*get_column) (RubricORMCursor* self, guint column, GValue* value);
	gboolean (*get_column_boolean) (RubricORMCursor* self, guint column);
	gdouble (*get_column_double) (RubricORMCursor* self, guint column);
	gfloat (*get_column_float) (RubricORMCursor* self, guint column);
	gint (*get_column_int) (RubricORMCursor* self, guint column);
	gint64 (*get_column_int64) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_name) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_string) (RubricORMCursor* self, guint column);
	guint (*get_column_uint) (RubricORMCursor* self, guint column);
	guint64 (*get_column_uint64) (RubricORMCursor* self, guint column);
	guint (*get_n_columns) (RubricORMCursor* self);
	gboolean (*next) (RubricORMCursor* self);
};

typedef enum  {
	RUBRIC_ORM_ERROR_ADAPTER_OPEN,
	RUBRIC_ORM_ERROR_COMMAND_NO_SQL,
	RUBRIC_ORM_ERROR_COMMAND_DRIVER,
	RUBRIC_ORM_ERROR_REPOSITORY_EMPTY_RESULT,
	RUBRIC_ORM_ERROR_RESOURCE_CURSOR,
	RUBRIC_ORM_ERROR_COMMAND_NO_REPOSITORY
} RubricORMError;
#define RUBRIC_ORM_ERROR rubric_orm_error_quark ()
struct _RubricORMCommandIface {
	GTypeInterface parent_iface;
	gboolean (*execute) (RubricORMCommand* self, RubricORMCursor** cursor, GError** error);
};



GType rubric_orm_cursor_get_type (void) G_GNUC_CONST;
GQuark rubric_orm_error_quark (void);
GType rubric_orm_command_get_type (void) G_GNUC_CONST;
gboolean rubric_orm_command_execute (RubricORMCommand* self, RubricORMCursor** cursor, GError** error);


gboolean rubric_orm_command_execute (RubricORMCommand* self, RubricORMCursor** cursor, GError** error) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/command.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/command.vala"
	return RUBRIC_ORM_COMMAND_GET_INTERFACE (self)->execute (self, cursor, error);
#line 94 "command.c"
}


static void rubric_orm_command_base_init (RubricORMCommandIface * iface) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/command.vala"
	static gboolean initialized = FALSE;
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/command.vala"
	if (!initialized) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/command.vala"
		initialized = TRUE;
#line 105 "command.c"
	}
}


GType rubric_orm_command_get_type (void) {
	static volatile gsize rubric_orm_command_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_command_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMCommandIface), (GBaseInitFunc) rubric_orm_command_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_command_type_id;
		rubric_orm_command_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMCommand", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_command_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_command_type_id__volatile, rubric_orm_command_type_id);
	}
	return rubric_orm_command_type_id__volatile;
}



