/* cursor.c generated by valac 0.32.1, the Vala compiler
 * generated from cursor.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define RUBRIC_ORM_TYPE_CURSOR (rubric_orm_cursor_get_type ())
#define RUBRIC_ORM_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursor))
#define RUBRIC_ORM_IS_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_CURSOR))
#define RUBRIC_ORM_CURSOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursorIface))

typedef struct _RubricORMCursor RubricORMCursor;
typedef struct _RubricORMCursorIface RubricORMCursorIface;

struct _RubricORMCursorIface {
	GTypeInterface parent_iface;
	void (*get_column) (RubricORMCursor* self, guint column, GValue* value);
	gboolean (*get_column_boolean) (RubricORMCursor* self, guint column);
	gdouble (*get_column_double) (RubricORMCursor* self, guint column);
	gfloat (*get_column_float) (RubricORMCursor* self, guint column);
	gint (*get_column_int) (RubricORMCursor* self, guint column);
	gint64 (*get_column_int64) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_name) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_string) (RubricORMCursor* self, guint column);
	guint (*get_column_uint) (RubricORMCursor* self, guint column);
	guint64 (*get_column_uint64) (RubricORMCursor* self, guint column);
	guint (*get_n_columns) (RubricORMCursor* self);
	gboolean (*next) (RubricORMCursor* self);
};



GType rubric_orm_cursor_get_type (void) G_GNUC_CONST;
void rubric_orm_cursor_get_column (RubricORMCursor* self, guint column, GValue* value);
gboolean rubric_orm_cursor_get_column_boolean (RubricORMCursor* self, guint column);
gdouble rubric_orm_cursor_get_column_double (RubricORMCursor* self, guint column);
gfloat rubric_orm_cursor_get_column_float (RubricORMCursor* self, guint column);
gint rubric_orm_cursor_get_column_int (RubricORMCursor* self, guint column);
gint64 rubric_orm_cursor_get_column_int64 (RubricORMCursor* self, guint column);
const gchar* rubric_orm_cursor_get_column_name (RubricORMCursor* self, guint column);
const gchar* rubric_orm_cursor_get_column_string (RubricORMCursor* self, guint column);
guint rubric_orm_cursor_get_column_uint (RubricORMCursor* self, guint column);
guint64 rubric_orm_cursor_get_column_uint64 (RubricORMCursor* self, guint column);
guint rubric_orm_cursor_get_n_columns (RubricORMCursor* self);
gboolean rubric_orm_cursor_next (RubricORMCursor* self);


void rubric_orm_cursor_get_column (RubricORMCursor* self, guint column, GValue* value) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column (self, column, value);
#line 81 "cursor.c"
}


gboolean rubric_orm_cursor_get_column_boolean (RubricORMCursor* self, guint column) {
#line 28 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 28 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_boolean (self, column);
#line 90 "cursor.c"
}


gdouble rubric_orm_cursor_get_column_double (RubricORMCursor* self, guint column) {
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_double (self, column);
#line 99 "cursor.c"
}


gfloat rubric_orm_cursor_get_column_float (RubricORMCursor* self, guint column) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0.0F);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_float (self, column);
#line 108 "cursor.c"
}


gint rubric_orm_cursor_get_column_int (RubricORMCursor* self, guint column) {
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_int (self, column);
#line 117 "cursor.c"
}


gint64 rubric_orm_cursor_get_column_int64 (RubricORMCursor* self, guint column) {
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0LL);
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_int64 (self, column);
#line 126 "cursor.c"
}


const gchar* rubric_orm_cursor_get_column_name (RubricORMCursor* self, guint column) {
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_name (self, column);
#line 135 "cursor.c"
}


const gchar* rubric_orm_cursor_get_column_string (RubricORMCursor* self, guint column) {
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_string (self, column);
#line 144 "cursor.c"
}


guint rubric_orm_cursor_get_column_uint (RubricORMCursor* self, guint column) {
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_uint (self, column);
#line 153 "cursor.c"
}


guint64 rubric_orm_cursor_get_column_uint64 (RubricORMCursor* self, guint column) {
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0ULL);
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_column_uint64 (self, column);
#line 162 "cursor.c"
}


guint rubric_orm_cursor_get_n_columns (RubricORMCursor* self) {
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->get_n_columns (self);
#line 171 "cursor.c"
}


gboolean rubric_orm_cursor_next (RubricORMCursor* self) {
#line 38 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 38 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	return RUBRIC_ORM_CURSOR_GET_INTERFACE (self)->next (self);
#line 180 "cursor.c"
}


static void rubric_orm_cursor_base_init (RubricORMCursorIface * iface) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	static gboolean initialized = FALSE;
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
	if (!initialized) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/cursor.vala"
		initialized = TRUE;
#line 191 "cursor.c"
	}
}


GType rubric_orm_cursor_get_type (void) {
	static volatile gsize rubric_orm_cursor_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_cursor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMCursorIface), (GBaseInitFunc) rubric_orm_cursor_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_cursor_type_id;
		rubric_orm_cursor_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMCursor", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_cursor_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_cursor_type_id__volatile, rubric_orm_cursor_type_id);
	}
	return rubric_orm_cursor_type_id__volatile;
}



