/* error.c generated by valac 0.32.1, the Vala compiler
 * generated from error.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


typedef enum  {
	RUBRIC_ORM_ERROR_ADAPTER_OPEN,
	RUBRIC_ORM_ERROR_COMMAND_NO_SQL,
	RUBRIC_ORM_ERROR_COMMAND_DRIVER,
	RUBRIC_ORM_ERROR_REPOSITORY_EMPTY_RESULT,
	RUBRIC_ORM_ERROR_RESOURCE_CURSOR,
	RUBRIC_ORM_ERROR_COMMAND_NO_REPOSITORY
} RubricORMError;
#define RUBRIC_ORM_ERROR rubric_orm_error_quark ()


GQuark rubric_orm_error_quark (void);


GQuark rubric_orm_error_quark (void) {
#line 24 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/messaging/messenger.vala"
	return g_quark_from_static_string ("rubric_orm_error-quark");
#line 48 "error.c"
}



