/* filter.c generated by valac 0.32.1, the Vala compiler
 * generated from filter.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define RUBRIC_ORM_TYPE_FILTER_MODE (rubric_orm_filter_mode_get_type ())

#define RUBRIC_ORM_TYPE_FILTER (rubric_orm_filter_get_type ())
#define RUBRIC_ORM_FILTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_FILTER, RubricORMFilter))
#define RUBRIC_ORM_IS_FILTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_FILTER))
#define RUBRIC_ORM_FILTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_FILTER, RubricORMFilterIface))

typedef struct _RubricORMFilter RubricORMFilter;
typedef struct _RubricORMFilterIface RubricORMFilterIface;

typedef enum  {
	RUBRIC_ORM_FILTER_MODE_SQL,
	RUBRIC_ORM_FILTER_MODE_OR,
	RUBRIC_ORM_FILTER_MODE_AND,
	RUBRIC_ORM_FILTER_MODE_EQ,
	RUBRIC_ORM_FILTER_MODE_NEQ,
	RUBRIC_ORM_FILTER_MODE_GT,
	RUBRIC_ORM_FILTER_MODE_GTE,
	RUBRIC_ORM_FILTER_MODE_LT,
	RUBRIC_ORM_FILTER_MODE_LTE,
	RUBRIC_ORM_FILTER_MODE_LIKE,
	RUBRIC_ORM_FILTER_MODE_GLOB,
	RUBRIC_ORM_FILTER_MODE_IS_NULL,
	RUBRIC_ORM_FILTER_MODE_IS_NOT_NULL
} RubricORMFilterMode;

struct _RubricORMFilterIface {
	GTypeInterface parent_iface;
};



GType rubric_orm_filter_mode_get_type (void) G_GNUC_CONST;
GType rubric_orm_filter_get_type (void) G_GNUC_CONST;


GType rubric_orm_filter_mode_get_type (void) {
	static volatile gsize rubric_orm_filter_mode_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_filter_mode_type_id__volatile)) {
		static const GEnumValue values[] = {{RUBRIC_ORM_FILTER_MODE_SQL, "RUBRIC_ORM_FILTER_MODE_SQL", "sql"}, {RUBRIC_ORM_FILTER_MODE_OR, "RUBRIC_ORM_FILTER_MODE_OR", "or"}, {RUBRIC_ORM_FILTER_MODE_AND, "RUBRIC_ORM_FILTER_MODE_AND", "and"}, {RUBRIC_ORM_FILTER_MODE_EQ, "RUBRIC_ORM_FILTER_MODE_EQ", "eq"}, {RUBRIC_ORM_FILTER_MODE_NEQ, "RUBRIC_ORM_FILTER_MODE_NEQ", "neq"}, {RUBRIC_ORM_FILTER_MODE_GT, "RUBRIC_ORM_FILTER_MODE_GT", "gt"}, {RUBRIC_ORM_FILTER_MODE_GTE, "RUBRIC_ORM_FILTER_MODE_GTE", "gte"}, {RUBRIC_ORM_FILTER_MODE_LT, "RUBRIC_ORM_FILTER_MODE_LT", "lt"}, {RUBRIC_ORM_FILTER_MODE_LTE, "RUBRIC_ORM_FILTER_MODE_LTE", "lte"}, {RUBRIC_ORM_FILTER_MODE_LIKE, "RUBRIC_ORM_FILTER_MODE_LIKE", "like"}, {RUBRIC_ORM_FILTER_MODE_GLOB, "RUBRIC_ORM_FILTER_MODE_GLOB", "glob"}, {RUBRIC_ORM_FILTER_MODE_IS_NULL, "RUBRIC_ORM_FILTER_MODE_IS_NULL", "is-null"}, {RUBRIC_ORM_FILTER_MODE_IS_NOT_NULL, "RUBRIC_ORM_FILTER_MODE_IS_NOT_NULL", "is-not-null"}, {0, NULL, NULL}};
		GType rubric_orm_filter_mode_type_id;
		rubric_orm_filter_mode_type_id = g_enum_register_static ("RubricORMFilterMode", values);
		g_once_init_leave (&rubric_orm_filter_mode_type_id__volatile, rubric_orm_filter_mode_type_id);
	}
	return rubric_orm_filter_mode_type_id__volatile;
}


static void rubric_orm_filter_base_init (RubricORMFilterIface * iface) {
#line 42 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/filter.vala"
	static gboolean initialized = FALSE;
#line 42 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/filter.vala"
	if (!initialized) {
#line 42 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/filter.vala"
		initialized = TRUE;
#line 86 "filter.c"
	}
}


GType rubric_orm_filter_get_type (void) {
	static volatile gsize rubric_orm_filter_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_filter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMFilterIface), (GBaseInitFunc) rubric_orm_filter_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_filter_type_id;
		rubric_orm_filter_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMFilter", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_filter_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_filter_type_id__volatile, rubric_orm_filter_type_id);
	}
	return rubric_orm_filter_type_id__volatile;
}



