/* resource-collection.c generated by valac 0.32.1, the Vala compiler
 * generated from resource-collection.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <gee.h>


#define RUBRIC_ORM_TYPE_RESOURCE_COLLECTION (rubric_orm_resource_collection_get_type ())
#define RUBRIC_ORM_RESOURCE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_RESOURCE_COLLECTION, RubricORMResourceCollection))
#define RUBRIC_ORM_IS_RESOURCE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_RESOURCE_COLLECTION))
#define RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_RESOURCE_COLLECTION, RubricORMResourceCollectionIface))

typedef struct _RubricORMResourceCollection RubricORMResourceCollection;
typedef struct _RubricORMResourceCollectionIface RubricORMResourceCollectionIface;

#define RUBRIC_ORM_TYPE_RESOURCE (rubric_orm_resource_get_type ())
#define RUBRIC_ORM_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResource))
#define RUBRIC_ORM_IS_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_RESOURCE))
#define RUBRIC_ORM_RESOURCE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResourceIface))

typedef struct _RubricORMResource RubricORMResource;
typedef struct _RubricORMResourceIface RubricORMResourceIface;

#define RUBRIC_ORM_TYPE_FILTER (rubric_orm_filter_get_type ())
#define RUBRIC_ORM_FILTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_FILTER, RubricORMFilter))
#define RUBRIC_ORM_IS_FILTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_FILTER))
#define RUBRIC_ORM_FILTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_FILTER, RubricORMFilterIface))

typedef struct _RubricORMFilter RubricORMFilter;
typedef struct _RubricORMFilterIface RubricORMFilterIface;

#define RUBRIC_ORM_TYPE_REPOSITORY (rubric_orm_repository_get_type ())
#define RUBRIC_ORM_REPOSITORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_REPOSITORY, RubricORMRepository))
#define RUBRIC_ORM_IS_REPOSITORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_REPOSITORY))
#define RUBRIC_ORM_REPOSITORY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_REPOSITORY, RubricORMRepositoryIface))

typedef struct _RubricORMRepository RubricORMRepository;
typedef struct _RubricORMRepositoryIface RubricORMRepositoryIface;

#define RUBRIC_ORM_TYPE_SORTING (rubric_orm_sorting_get_type ())
#define RUBRIC_ORM_SORTING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_SORTING, RubricORMSorting))
#define RUBRIC_ORM_IS_SORTING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_SORTING))
#define RUBRIC_ORM_SORTING_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_SORTING, RubricORMSortingIface))

typedef struct _RubricORMSorting RubricORMSorting;
typedef struct _RubricORMSortingIface RubricORMSortingIface;

#define RUBRIC_ORM_TYPE_ADAPTER (rubric_orm_adapter_get_type ())
#define RUBRIC_ORM_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_ADAPTER, RubricORMAdapter))
#define RUBRIC_ORM_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_ADAPTER))
#define RUBRIC_ORM_ADAPTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_ADAPTER, RubricORMAdapterIface))

typedef struct _RubricORMAdapter RubricORMAdapter;
typedef struct _RubricORMAdapterIface RubricORMAdapterIface;

#define RUBRIC_ORM_TYPE_COMMAND_BUILDER (rubric_orm_command_builder_get_type ())
#define RUBRIC_ORM_COMMAND_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER, RubricORMCommandBuilder))
#define RUBRIC_ORM_IS_COMMAND_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER))
#define RUBRIC_ORM_COMMAND_BUILDER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_COMMAND_BUILDER, RubricORMCommandBuilderIface))

typedef struct _RubricORMCommandBuilder RubricORMCommandBuilder;
typedef struct _RubricORMCommandBuilderIface RubricORMCommandBuilderIface;

#define RUBRIC_ORM_TYPE_COMMAND (rubric_orm_command_get_type ())
#define RUBRIC_ORM_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommand))
#define RUBRIC_ORM_IS_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_COMMAND))
#define RUBRIC_ORM_COMMAND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_COMMAND, RubricORMCommandIface))

typedef struct _RubricORMCommand RubricORMCommand;
typedef struct _RubricORMCommandIface RubricORMCommandIface;

#define RUBRIC_ORM_TYPE_CURSOR (rubric_orm_cursor_get_type ())
#define RUBRIC_ORM_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursor))
#define RUBRIC_ORM_IS_CURSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_CURSOR))
#define RUBRIC_ORM_CURSOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_CURSOR, RubricORMCursorIface))

typedef struct _RubricORMCursor RubricORMCursor;
typedef struct _RubricORMCursorIface RubricORMCursorIface;

typedef enum  {
	RUBRIC_ORM_ERROR_ADAPTER_OPEN,
	RUBRIC_ORM_ERROR_COMMAND_NO_SQL,
	RUBRIC_ORM_ERROR_COMMAND_DRIVER,
	RUBRIC_ORM_ERROR_REPOSITORY_EMPTY_RESULT,
	RUBRIC_ORM_ERROR_RESOURCE_CURSOR,
	RUBRIC_ORM_ERROR_COMMAND_NO_REPOSITORY
} RubricORMError;
#define RUBRIC_ORM_ERROR rubric_orm_error_quark ()
struct _RubricORMResourceIface {
	GTypeInterface parent_iface;
};

struct _RubricORMFilterIface {
	GTypeInterface parent_iface;
};

struct _RubricORMSortingIface {
	GTypeInterface parent_iface;
};

struct _RubricORMCursorIface {
	GTypeInterface parent_iface;
	void (*get_column) (RubricORMCursor* self, guint column, GValue* value);
	gboolean (*get_column_boolean) (RubricORMCursor* self, guint column);
	gdouble (*get_column_double) (RubricORMCursor* self, guint column);
	gfloat (*get_column_float) (RubricORMCursor* self, guint column);
	gint (*get_column_int) (RubricORMCursor* self, guint column);
	gint64 (*get_column_int64) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_name) (RubricORMCursor* self, guint column);
	const gchar* (*get_column_string) (RubricORMCursor* self, guint column);
	guint (*get_column_uint) (RubricORMCursor* self, guint column);
	guint64 (*get_column_uint64) (RubricORMCursor* self, guint column);
	guint (*get_n_columns) (RubricORMCursor* self);
	gboolean (*next) (RubricORMCursor* self);
};

struct _RubricORMCommandIface {
	GTypeInterface parent_iface;
	gboolean (*execute) (RubricORMCommand* self, RubricORMCursor** cursor, GError** error);
};

struct _RubricORMCommandBuilderIface {
	GTypeInterface parent_iface;
	RubricORMCommand* (*build_count) (RubricORMCommandBuilder* self);
	GeeList* (*build_create) (RubricORMCommandBuilder* self, guint version);
	RubricORMCommand* (*build_delete) (RubricORMCommandBuilder* self);
	RubricORMCommand* (*build_insert) (RubricORMCommandBuilder* self, RubricORMResource* resource);
	RubricORMCommand* (*build_select) (RubricORMCommandBuilder* self);
	RubricORMCommand* (*build_update) (RubricORMCommandBuilder* self, RubricORMResource* resource);
};

struct _RubricORMAdapterIface {
	GTypeInterface parent_iface;
	gboolean (*execute_sql) (RubricORMAdapter* self, const gchar* sql, GError** error);
	void (*open_async) (RubricORMAdapter* self, const gchar* uri, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*open_finish) (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
	gboolean (*open) (RubricORMAdapter* self, const gchar* uri, GError** error);
	gboolean (*close) (RubricORMAdapter* self, GError** error);
	void (*close_async) (RubricORMAdapter* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*close_finish) (RubricORMAdapter* self, GAsyncResult* _res_, GError** error);
	void* (*get_handle) (RubricORMAdapter* self);
	RubricORMCommandBuilder* (*get_command_builder) (RubricORMAdapter* self, GParameter* parameters, int parameters_length1);
};

struct _RubricORMRepositoryIface {
	GTypeInterface parent_iface;
	RubricORMResourceCollection* (*find) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, GError** error);
	void (*find_async) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RubricORMResourceCollection* (*find_finish) (RubricORMRepository* self, GAsyncResult* _res_, GError** error);
	RubricORMResource* (*find_one) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, GError** error);
	void (*find_one_async) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RubricORMResource* (*find_one_finish) (RubricORMRepository* self, GAsyncResult* _res_, GError** error);
	RubricORMResourceCollection* (*find_sorted) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, RubricORMSorting* sorting, GError** error);
	void (*find_sorted_async) (RubricORMRepository* self, GType resource_type, RubricORMFilter* filter, RubricORMSorting* sorting, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RubricORMResourceCollection* (*find_sorted_finish) (RubricORMRepository* self, GAsyncResult* _res_);
	RubricORMAdapter* (*get_adapter) (RubricORMRepository* self);
	void (*set_adapter) (RubricORMRepository* self, RubricORMAdapter* value);
};

struct _RubricORMResourceCollectionIface {
	GTypeInterface parent_iface;
	gboolean (*fetch) (RubricORMResourceCollection* self, guint index, guint count, GError** error);
	RubricORMResource* (*get_index) (RubricORMResourceCollection* self, guint index);
	gint (*get_count) (RubricORMResourceCollection* self);
	void (*set_count) (RubricORMResourceCollection* self, gint value);
	RubricORMFilter* (*get_filter) (RubricORMResourceCollection* self);
	void (*set_filter) (RubricORMResourceCollection* self, RubricORMFilter* value);
	gboolean (*get_is_writable) (RubricORMResourceCollection* self);
	void (*set_is_writable) (RubricORMResourceCollection* self, gboolean value);
	const gchar* (*get_m2m_table) (RubricORMResourceCollection* self);
	void (*set_m2m_table) (RubricORMResourceCollection* self, const gchar* value);
	GType (*get_m2m_type) (RubricORMResourceCollection* self);
	void (*set_m2m_type) (RubricORMResourceCollection* self, GType value);
	RubricORMRepository* (*get_repository) (RubricORMResourceCollection* self);
	void (*set_repository) (RubricORMResourceCollection* self, RubricORMRepository* value);
	GType (*get_resource_type) (RubricORMResourceCollection* self);
	void (*set_resource_type) (RubricORMResourceCollection* self, GType value);
	RubricORMSorting* (*get_sorting) (RubricORMResourceCollection* self);
	void (*set_sorting) (RubricORMResourceCollection* self, RubricORMSorting* value);
};



GQuark rubric_orm_error_quark (void);
GType rubric_orm_resource_get_type (void) G_GNUC_CONST;
GType rubric_orm_filter_get_type (void) G_GNUC_CONST;
GType rubric_orm_sorting_get_type (void) G_GNUC_CONST;
GType rubric_orm_cursor_get_type (void) G_GNUC_CONST;
GType rubric_orm_command_get_type (void) G_GNUC_CONST;
GType rubric_orm_command_builder_get_type (void) G_GNUC_CONST;
GType rubric_orm_adapter_get_type (void) G_GNUC_CONST;
GType rubric_orm_repository_get_type (void) G_GNUC_CONST;
GType rubric_orm_resource_collection_get_type (void) G_GNUC_CONST;
gboolean rubric_orm_resource_collection_fetch (RubricORMResourceCollection* self, guint index, guint count, GError** error);
RubricORMResource* rubric_orm_resource_collection_get_index (RubricORMResourceCollection* self, guint index);
gint rubric_orm_resource_collection_get_count (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_count (RubricORMResourceCollection* self, gint value);
RubricORMFilter* rubric_orm_resource_collection_get_filter (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_filter (RubricORMResourceCollection* self, RubricORMFilter* value);
gboolean rubric_orm_resource_collection_get_is_writable (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_is_writable (RubricORMResourceCollection* self, gboolean value);
const gchar* rubric_orm_resource_collection_get_m2m_table (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_m2m_table (RubricORMResourceCollection* self, const gchar* value);
GType rubric_orm_resource_collection_get_m2m_type (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_m2m_type (RubricORMResourceCollection* self, GType value);
RubricORMRepository* rubric_orm_resource_collection_get_repository (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_repository (RubricORMResourceCollection* self, RubricORMRepository* value);
GType rubric_orm_resource_collection_get_resource_type (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_resource_type (RubricORMResourceCollection* self, GType value);
RubricORMSorting* rubric_orm_resource_collection_get_sorting (RubricORMResourceCollection* self);
static void rubric_orm_resource_collection_set_sorting (RubricORMResourceCollection* self, RubricORMSorting* value);


gboolean rubric_orm_resource_collection_fetch (RubricORMResourceCollection* self, guint index, guint count, GError** error) {
#line 43 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 43 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->fetch (self, index, count, error);
#line 248 "resource-collection.c"
}


RubricORMResource* rubric_orm_resource_collection_get_index (RubricORMResourceCollection* self, guint index) {
#line 45 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 45 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_index (self, index);
#line 257 "resource-collection.c"
}


gint rubric_orm_resource_collection_get_count (RubricORMResourceCollection* self) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_count (self);
#line 266 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_count (RubricORMResourceCollection* self, gint value) {
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_count (self, value);
#line 275 "resource-collection.c"
}


RubricORMFilter* rubric_orm_resource_collection_get_filter (RubricORMResourceCollection* self) {
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_filter (self);
#line 284 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_filter (RubricORMResourceCollection* self, RubricORMFilter* value) {
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 29 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_filter (self, value);
#line 293 "resource-collection.c"
}


gboolean rubric_orm_resource_collection_get_is_writable (RubricORMResourceCollection* self) {
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_is_writable (self);
#line 302 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_is_writable (RubricORMResourceCollection* self, gboolean value) {
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 31 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_is_writable (self, value);
#line 311 "resource-collection.c"
}


const gchar* rubric_orm_resource_collection_get_m2m_table (RubricORMResourceCollection* self) {
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_m2m_table (self);
#line 320 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_m2m_table (RubricORMResourceCollection* self, const gchar* value) {
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 33 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_m2m_table (self, value);
#line 329 "resource-collection.c"
}


GType rubric_orm_resource_collection_get_m2m_type (RubricORMResourceCollection* self) {
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, 0UL);
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_m2m_type (self);
#line 338 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_m2m_type (RubricORMResourceCollection* self, GType value) {
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_m2m_type (self, value);
#line 347 "resource-collection.c"
}


RubricORMRepository* rubric_orm_resource_collection_get_repository (RubricORMResourceCollection* self) {
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_repository (self);
#line 356 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_repository (RubricORMResourceCollection* self, RubricORMRepository* value) {
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 37 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_repository (self, value);
#line 365 "resource-collection.c"
}


GType rubric_orm_resource_collection_get_resource_type (RubricORMResourceCollection* self) {
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, 0UL);
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_resource_type (self);
#line 374 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_resource_type (RubricORMResourceCollection* self, GType value) {
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_resource_type (self, value);
#line 383 "resource-collection.c"
}


RubricORMSorting* rubric_orm_resource_collection_get_sorting (RubricORMResourceCollection* self) {
#line 41 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 41 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	return RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->get_sorting (self);
#line 392 "resource-collection.c"
}


static void rubric_orm_resource_collection_set_sorting (RubricORMResourceCollection* self, RubricORMSorting* value) {
#line 41 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	g_return_if_fail (self != NULL);
#line 41 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	RUBRIC_ORM_RESOURCE_COLLECTION_GET_INTERFACE (self)->set_sorting (self, value);
#line 401 "resource-collection.c"
}


static void rubric_orm_resource_collection_base_init (RubricORMResourceCollectionIface * iface) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	static gboolean initialized = FALSE;
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
	if (!initialized) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		initialized = TRUE;
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_int ("count", "count", "count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_object ("filter", "filter", "filter", RUBRIC_ORM_TYPE_FILTER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_boolean ("is-writable", "is-writable", "is-writable", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_string ("m2m-table", "m2m-table", "m2m-table", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_gtype ("m2m-type", "m2m-type", "m2m-type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_object ("repository", "repository", "repository", RUBRIC_ORM_TYPE_REPOSITORY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_gtype ("resource-type", "resource-type", "resource-type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource-collection.vala"
		g_object_interface_install_property (iface, g_param_spec_object ("sorting", "sorting", "sorting", RUBRIC_ORM_TYPE_SORTING, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 428 "resource-collection.c"
	}
}


GType rubric_orm_resource_collection_get_type (void) {
	static volatile gsize rubric_orm_resource_collection_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_resource_collection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMResourceCollectionIface), (GBaseInitFunc) rubric_orm_resource_collection_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_resource_collection_type_id;
		rubric_orm_resource_collection_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMResourceCollection", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_resource_collection_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_resource_collection_type_id__volatile, rubric_orm_resource_collection_type_id);
	}
	return rubric_orm_resource_collection_type_id__volatile;
}



