/* resource.c generated by valac 0.32.1, the Vala compiler
 * generated from resource.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define RUBRIC_ORM_TYPE_RESOURCE (rubric_orm_resource_get_type ())
#define RUBRIC_ORM_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResource))
#define RUBRIC_ORM_IS_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_RESOURCE))
#define RUBRIC_ORM_RESOURCE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_RESOURCE, RubricORMResourceIface))

typedef struct _RubricORMResource RubricORMResource;
typedef struct _RubricORMResourceIface RubricORMResourceIface;

struct _RubricORMResourceIface {
	GTypeInterface parent_iface;
};



GType rubric_orm_resource_get_type (void) G_GNUC_CONST;


static void rubric_orm_resource_base_init (RubricORMResourceIface * iface) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource.vala"
	static gboolean initialized = FALSE;
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource.vala"
	if (!initialized) {
#line 25 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/resource.vala"
		initialized = TRUE;
#line 55 "resource.c"
	}
}


GType rubric_orm_resource_get_type (void) {
	static volatile gsize rubric_orm_resource_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_resource_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMResourceIface), (GBaseInitFunc) rubric_orm_resource_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_resource_type_id;
		rubric_orm_resource_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMResource", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_resource_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_resource_type_id__volatile, rubric_orm_resource_type_id);
	}
	return rubric_orm_resource_type_id__volatile;
}



