/* sorting.c generated by valac 0.32.1, the Vala compiler
 * generated from sorting.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <bizarro@localhost.localdomain>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define RUBRIC_ORM_TYPE_SORTING_MODE (rubric_orm_sorting_mode_get_type ())

#define RUBRIC_ORM_TYPE_SORTING (rubric_orm_sorting_get_type ())
#define RUBRIC_ORM_SORTING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_ORM_TYPE_SORTING, RubricORMSorting))
#define RUBRIC_ORM_IS_SORTING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_ORM_TYPE_SORTING))
#define RUBRIC_ORM_SORTING_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RUBRIC_ORM_TYPE_SORTING, RubricORMSortingIface))

typedef struct _RubricORMSorting RubricORMSorting;
typedef struct _RubricORMSortingIface RubricORMSortingIface;

typedef enum  {
	RUBRIC_ORM_SORTING_MODE_ASCENDING,
	RUBRIC_ORM_SORTING_MODE_DESCENDING
} RubricORMSortingMode;

struct _RubricORMSortingIface {
	GTypeInterface parent_iface;
};



GType rubric_orm_sorting_mode_get_type (void) G_GNUC_CONST;
GType rubric_orm_sorting_get_type (void) G_GNUC_CONST;


GType rubric_orm_sorting_mode_get_type (void) {
	static volatile gsize rubric_orm_sorting_mode_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_sorting_mode_type_id__volatile)) {
		static const GEnumValue values[] = {{RUBRIC_ORM_SORTING_MODE_ASCENDING, "RUBRIC_ORM_SORTING_MODE_ASCENDING", "ascending"}, {RUBRIC_ORM_SORTING_MODE_DESCENDING, "RUBRIC_ORM_SORTING_MODE_DESCENDING", "descending"}, {0, NULL, NULL}};
		GType rubric_orm_sorting_mode_type_id;
		rubric_orm_sorting_mode_type_id = g_enum_register_static ("RubricORMSortingMode", values);
		g_once_init_leave (&rubric_orm_sorting_mode_type_id__volatile, rubric_orm_sorting_mode_type_id);
	}
	return rubric_orm_sorting_mode_type_id__volatile;
}


static void rubric_orm_sorting_base_init (RubricORMSortingIface * iface) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/sorting.vala"
	static gboolean initialized = FALSE;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/sorting.vala"
	if (!initialized) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/librubric/src/orm/sorting.vala"
		initialized = TRUE;
#line 75 "sorting.c"
	}
}


GType rubric_orm_sorting_get_type (void) {
	static volatile gsize rubric_orm_sorting_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_orm_sorting_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricORMSortingIface), (GBaseInitFunc) rubric_orm_sorting_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType rubric_orm_sorting_type_id;
		rubric_orm_sorting_type_id = g_type_register_static (G_TYPE_INTERFACE, "RubricORMSorting", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (rubric_orm_sorting_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&rubric_orm_sorting_type_id__volatile, rubric_orm_sorting_type_id);
	}
	return rubric_orm_sorting_type_id__volatile;
}



