/* test-v8.vapi generated by valac 0.34.7, do not modify. */

[CCode (cprefix = "RubricWebV8", gir_namespace = "RubricWebV8", gir_version = "1.0", lower_case_cprefix = "rubric_web_v8_")]
namespace RubricWebV8 {
	namespace Tests {
		[CCode (cheader_filename = "v8.h")]
		public class V8JSEngine : Valadate.Framework.TestCase {
			public V8JSEngine ();
			public void test_calling_of_function_with_boolean_result ();
			public void test_calling_of_function_with_double_result ();
			public void test_calling_of_function_with_integer_result ();
			public void test_calling_of_function_with_many_parameters ();
			public void test_calling_of_function_with_many_parameters_and_boolean_result ();
			public void test_calling_of_function_with_many_parameters_and_double_result ();
			public void test_calling_of_function_with_many_parameters_and_integer_result ();
			public void test_calling_of_function_with_many_parameters_and_string_result ();
			public void test_calling_of_function_with_many_parameters_and_unicode_string_result ();
			public void test_calling_of_function_with_null_result ();
			public void test_calling_of_function_with_string_result ();
			public void test_calling_of_function_with_undefined_result ();
			public void test_calling_of_function_with_unicode_string_result ();
			public void test_calling_of_function_without_parameters ();
			public void test_eval_expression_bool_result ();
			public void test_eval_expression_double_result ();
			public void test_eval_expression_integer_result ();
			public void test_eval_expression_null_result ();
			public void test_eval_expression_string_result ();
			public void test_eval_expression_unicode_string_result ();
			public void test_execution_of_code ();
			public void test_execution_of_file ();
			public void test_garbage_collection ();
			public void test_new_engine ();
			public void test_removing_variable ();
			public void test_setting_and_getting_variable_with_boolean ();
			public void test_setting_and_getting_variable_with_double ();
			public void test_setting_and_getting_variable_with_integer ();
			public void test_setting_and_getting_variable_with_null ();
			public void test_setting_and_getting_variable_with_string ();
			public void test_setting_and_getting_variable_with_undefined ();
			public void test_setting_and_getting_variable_with_unicode_string ();
		}
	}
}
