/* es-5.c generated by valac 0.34.7, the Vala compiler
 * generated from es-5.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libvaladate-1.0.h>
#include <stdlib.h>
#include <string.h>
#include <libmujs.h>
#include <rubric-web.h>
#include <float.h>
#include <math.h>


#define RUBRIC_WEB_MUJS_TESTS_TYPE_ES5 (rubric_web_mujs_tests_es5_get_type ())
#define RUBRIC_WEB_MUJS_TESTS_ES5(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_ES5, RubricWebMujsTestsEs5))
#define RUBRIC_WEB_MUJS_TESTS_ES5_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUBRIC_WEB_MUJS_TESTS_TYPE_ES5, RubricWebMujsTestsEs5Class))
#define RUBRIC_WEB_MUJS_TESTS_IS_ES5(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_ES5))
#define RUBRIC_WEB_MUJS_TESTS_IS_ES5_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUBRIC_WEB_MUJS_TESTS_TYPE_ES5))
#define RUBRIC_WEB_MUJS_TESTS_ES5_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_ES5, RubricWebMujsTestsEs5Class))

typedef struct _RubricWebMujsTestsEs5 RubricWebMujsTestsEs5;
typedef struct _RubricWebMujsTestsEs5Class RubricWebMujsTestsEs5Class;
typedef struct _RubricWebMujsTestsEs5Private RubricWebMujsTestsEs5Private;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _rubric_web_undefined_unref0(var) ((var == NULL) ? NULL : (var = (rubric_web_undefined_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _RubricWebMujsTestsEs5 {
	ValadateFrameworkTestCase parent_instance;
	RubricWebMujsTestsEs5Private * priv;
};

struct _RubricWebMujsTestsEs5Class {
	ValadateFrameworkTestCaseClass parent_class;
};


static gpointer rubric_web_mujs_tests_es5_parent_class = NULL;

GType rubric_web_mujs_tests_es5_get_type (void) G_GNUC_CONST;
enum  {
	RUBRIC_WEB_MUJS_TESTS_ES5_DUMMY_PROPERTY
};
void rubric_web_mujs_tests_es5_test_array_every_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_filter_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_for_each_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_index_of_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_is_array_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_last_index_of_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_map_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_reduce_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_reduce_right_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_array_some_method_is_supported (RubricWebMujsTestsEs5* self);
void _rubric_web_mujs_tests_es5_test_date_now_method_is_supported (RubricWebMujsTestsEs5* self);
static gdouble* _double_dup (gdouble* self);
void rubric_web_mujs_tests_es5_test_date_to_iso_string_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_function_bind_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_json_parse_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_json_stringify_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_object_create_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_object_keys_method_is_supported (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_string_split_method (RubricWebMujsTestsEs5* self);
void rubric_web_mujs_tests_es5_test_string_trim_method_is_supported (RubricWebMujsTestsEs5* self);
RubricWebMujsTestsEs5* rubric_web_mujs_tests_es5_new (void);
RubricWebMujsTestsEs5* rubric_web_mujs_tests_es5_construct (GType object_type);


void rubric_web_mujs_tests_es5_test_array_every_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var engines = ['Chakra', 'V8', 'SpiderMonkey', 'Jurassic'];";
	static const char input1[] = "engines.every(function (value, index, array) { return value.length > 1" \
"; });";
	static const gboolean targetOutput1 = TRUE;
	static const char input2[] = "engines.every(function (value, index, array) { return value.length < 1" \
"0; });";
	static const gboolean targetOutput2 = FALSE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean output1 = FALSE;
	gboolean output2 = FALSE;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	RubricWebMujsEngine* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_BOOLEAN, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp2_ = (gboolean) ((gintptr) _tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp2_;
	_tmp6_ = engine;
	_tmp7_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_BOOLEAN, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp5_ = (gboolean) ((gintptr) _tmp7_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp5_;
	_tmp8_ = output1;
	_vala_assert (targetOutput1 == _tmp8_, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (targetOutput2 == _tmp9_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_filter_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var engines = ['Chakra', 'V8', 'SpiderMonkey', 'Jurassic'];";
	static const char input[] = "engines\n" \
"	.filter(\n" \
"		function (value, index, array) {\n" \
"			return value.length > 5;\n" \
"		})\n" \
"	.toString();";
	static const char targetOutput[] = "Chakra,SpiderMonkey,Jurassic";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp2_ = (gchar*) _tmp4_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = _tmp2_;
	_tmp2_ = NULL;
	_g_free0 (output);
	output = _tmp5_;
	_tmp6_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp6_) == 0, "targetOutput == output");
	_g_free0 (_tmp2_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_for_each_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char resultVariableName[] = "enginesString";
	gchar* initCode = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	static const char targetOutput[] = "Chakra;V8;SpiderMonkey;Jurassic";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gchar* output = NULL;
	const gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("var engines = ['Chakra', 'V8', 'SpiderMonkey', 'Jurassic'],\n" \
"\t%s = ''\n" \
"\t;\n" \
"\n" \
"engines.forEach(function(value, index, array) {{\n" \
"\tif (index > 0) {{\n" \
"\t\t%s += ';';\n" \
"\t}}\n" \
"\t%s += value;\n" \
"}});");
	initCode = _tmp0_;
	_tmp1_ = initCode;
	_tmp2_ = g_strdup_printf (_tmp1_, resultVariableName, resultVariableName, resultVariableName);
	_g_free0 (initCode);
	initCode = _tmp2_;
	_tmp3_ = rubric_web_mujs_engine_new ();
	engine = _tmp3_;
	_tmp4_ = initCode;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		_g_free0 (initCode);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, resultVariableName);
	_g_free0 (output);
	output = (gchar*) _tmp5_;
	_tmp6_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp6_) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
	_g_free0 (initCode);
}


void rubric_web_mujs_tests_es5_test_array_index_of_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var arr = [2, 5, 9, 2]";
	static const char input1[] = "arr.indexOf(2);";
	static const gint targetOutput1 = 0;
	static const char input2[] = "arr.indexOf(7);";
	static const gint targetOutput2 = -1;
	static const char input3[] = "arr.indexOf(2, 3)";
	static const gint targetOutput3 = 3;
	static const char input4[] = "arr.indexOf(2, 2);";
	static const gint targetOutput4 = 3;
	static const char input5[] = "arr.indexOf(2, -2);";
	static const gint targetOutput5 = 3;
	static const char input6[] = "arr.indexOf(2, -1);";
	static const gint targetOutput6 = 3;
	static const char input7[] = "[].lastIndexOf(2, 0);";
	static const gint targetOutput7 = -1;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	gint output3 = 0;
	gint output4 = 0;
	gint output5 = 0;
	gint output6 = 0;
	gint output7 = 0;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	RubricWebMujsEngine* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gint _tmp8_ = 0;
	RubricWebMujsEngine* _tmp9_ = NULL;
	gpointer _tmp10_ = NULL;
	gint _tmp11_ = 0;
	RubricWebMujsEngine* _tmp12_ = NULL;
	gpointer _tmp13_ = NULL;
	gint _tmp14_ = 0;
	RubricWebMujsEngine* _tmp15_ = NULL;
	gpointer _tmp16_ = NULL;
	gint _tmp17_ = 0;
	RubricWebMujsEngine* _tmp18_ = NULL;
	gpointer _tmp19_ = NULL;
	gint _tmp20_ = 0;
	RubricWebMujsEngine* _tmp21_ = NULL;
	gpointer _tmp22_ = NULL;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp2_ = (gint) ((gintptr) _tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp2_;
	_tmp6_ = engine;
	_tmp7_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp5_ = (gint) ((gintptr) _tmp7_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp5_;
	_tmp9_ = engine;
	_tmp10_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp9_, G_TYPE_INT, NULL, NULL, input3, NULL, &_inner_error_);
	_tmp8_ = (gint) ((gintptr) _tmp10_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output3 = _tmp8_;
	_tmp12_ = engine;
	_tmp13_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp12_, G_TYPE_INT, NULL, NULL, input4, NULL, &_inner_error_);
	_tmp11_ = (gint) ((gintptr) _tmp13_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output4 = _tmp11_;
	_tmp15_ = engine;
	_tmp16_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp15_, G_TYPE_INT, NULL, NULL, input5, NULL, &_inner_error_);
	_tmp14_ = (gint) ((gintptr) _tmp16_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output5 = _tmp14_;
	_tmp18_ = engine;
	_tmp19_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp18_, G_TYPE_INT, NULL, NULL, input6, NULL, &_inner_error_);
	_tmp17_ = (gint) ((gintptr) _tmp19_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output6 = _tmp17_;
	_tmp21_ = engine;
	_tmp22_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp21_, G_TYPE_INT, NULL, NULL, input7, NULL, &_inner_error_);
	_tmp20_ = (gint) ((gintptr) _tmp22_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output7 = _tmp20_;
	_tmp23_ = output1;
	_vala_assert (targetOutput1 == _tmp23_, "targetOutput1 == output1");
	_tmp24_ = output2;
	_vala_assert (targetOutput2 == _tmp24_, "targetOutput2 == output2");
	_tmp25_ = output3;
	_vala_assert (targetOutput3 == _tmp25_, "targetOutput3 == output3");
	_tmp26_ = output4;
	_vala_assert (targetOutput4 == _tmp26_, "targetOutput4 == output4");
	_tmp27_ = output5;
	_vala_assert (targetOutput5 == _tmp27_, "targetOutput5 == output5");
	_tmp28_ = output6;
	_vala_assert (targetOutput6 == _tmp28_, "targetOutput6 == output6");
	_tmp29_ = output7;
	_vala_assert (targetOutput7 == _tmp29_, "targetOutput7 == output7");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_is_array_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input1[] = "Array.isArray({ length: 0 });";
	static const gboolean targetOutput1 = FALSE;
	static const char input2[] = "Array.isArray([1, 2, 3, 4, 5]);";
	static const gboolean targetOutput2 = TRUE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean output1 = FALSE;
	gboolean output2 = FALSE;
	gboolean _tmp1_ = FALSE;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	RubricWebMujsEngine* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	gboolean _tmp8_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_BOOLEAN, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp1_ = (gboolean) ((gintptr) _tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp1_;
	_tmp5_ = engine;
	_tmp6_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp5_, G_TYPE_BOOLEAN, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp4_ = (gboolean) ((gintptr) _tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp4_;
	_tmp7_ = output1;
	_vala_assert (targetOutput1 == _tmp7_, "targetOutput1 == output1");
	_tmp8_ = output2;
	_vala_assert (targetOutput2 == _tmp8_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_last_index_of_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var arr = [2, 5, 9, 2]";
	static const char input1[] = "arr.lastIndexOf(2);";
	static const gint targetOutput1 = 3;
	static const char input2[] = "arr.lastIndexOf(7);";
	static const gint targetOutput2 = -1;
	static const char input3[] = "arr.lastIndexOf(2, 3)";
	static const gint targetOutput3 = 3;
	static const char input4[] = "arr.lastIndexOf(2, 2);";
	static const gint targetOutput4 = 0;
	static const char input5[] = "arr.lastIndexOf(2, -2);";
	static const gint targetOutput5 = 0;
	static const char input6[] = "arr.lastIndexOf(2, -1);";
	static const gint targetOutput6 = 3;
	static const char input7[] = "[].lastIndexOf(2, 0);";
	static const gint targetOutput7 = -1;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	gint output3 = 0;
	gint output4 = 0;
	gint output5 = 0;
	gint output6 = 0;
	gint output7 = 0;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	RubricWebMujsEngine* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gint _tmp8_ = 0;
	RubricWebMujsEngine* _tmp9_ = NULL;
	gpointer _tmp10_ = NULL;
	gint _tmp11_ = 0;
	RubricWebMujsEngine* _tmp12_ = NULL;
	gpointer _tmp13_ = NULL;
	gint _tmp14_ = 0;
	RubricWebMujsEngine* _tmp15_ = NULL;
	gpointer _tmp16_ = NULL;
	gint _tmp17_ = 0;
	RubricWebMujsEngine* _tmp18_ = NULL;
	gpointer _tmp19_ = NULL;
	gint _tmp20_ = 0;
	RubricWebMujsEngine* _tmp21_ = NULL;
	gpointer _tmp22_ = NULL;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp2_ = (gint) ((gintptr) _tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp2_;
	_tmp6_ = engine;
	_tmp7_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp5_ = (gint) ((gintptr) _tmp7_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp5_;
	_tmp9_ = engine;
	_tmp10_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp9_, G_TYPE_INT, NULL, NULL, input3, NULL, &_inner_error_);
	_tmp8_ = (gint) ((gintptr) _tmp10_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output3 = _tmp8_;
	_tmp12_ = engine;
	_tmp13_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp12_, G_TYPE_INT, NULL, NULL, input4, NULL, &_inner_error_);
	_tmp11_ = (gint) ((gintptr) _tmp13_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output4 = _tmp11_;
	_tmp15_ = engine;
	_tmp16_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp15_, G_TYPE_INT, NULL, NULL, input5, NULL, &_inner_error_);
	_tmp14_ = (gint) ((gintptr) _tmp16_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output5 = _tmp14_;
	_tmp18_ = engine;
	_tmp19_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp18_, G_TYPE_INT, NULL, NULL, input6, NULL, &_inner_error_);
	_tmp17_ = (gint) ((gintptr) _tmp19_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output6 = _tmp17_;
	_tmp21_ = engine;
	_tmp22_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp21_, G_TYPE_INT, NULL, NULL, input7, NULL, &_inner_error_);
	_tmp20_ = (gint) ((gintptr) _tmp22_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output7 = _tmp20_;
	_tmp23_ = output1;
	_vala_assert (targetOutput1 == _tmp23_, "targetOutput1 == output1");
	_tmp24_ = output2;
	_vala_assert (targetOutput2 == _tmp24_, "targetOutput2 == output2");
	_tmp25_ = output3;
	_vala_assert (targetOutput3 == _tmp25_, "targetOutput3 == output3");
	_tmp26_ = output4;
	_vala_assert (targetOutput4 == _tmp26_, "targetOutput4 == output4");
	_tmp27_ = output5;
	_vala_assert (targetOutput5 == _tmp27_, "targetOutput5 == output5");
	_tmp28_ = output6;
	_vala_assert (targetOutput6 == _tmp28_, "targetOutput6 == output6");
	_tmp29_ = output7;
	_vala_assert (targetOutput7 == _tmp29_, "targetOutput7 == output7");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_map_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var engines = ['Chakra', 'V8', 'SpiderMonkey', 'Jurassic'];";
	static const char input[] = "engines\n" \
"	.map(\n" \
"		function (value, index, array) {\n" \
"			return value + ' JS Engine';\n" \
"		})\n" \
"	.toString();";
	static const char targetOutput[] = "Chakra JS Engine,V8 JS Engine,SpiderMonkey JS Engine,Jurassic JS Engin" \
"e";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp2_ = (gchar*) _tmp4_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = _tmp2_;
	_tmp2_ = NULL;
	_g_free0 (output);
	output = _tmp5_;
	_tmp6_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp6_) == 0, "targetOutput == output");
	_g_free0 (_tmp2_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_reduce_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input1[] = "[1, 2, 3, 4, 5].reduce(function (accum, value, index, array) {\n" \
"	return accum + value;\n" \
"});";
	static const gint targetOutput1 = 15;
	static const char input2[] = "[1, 2, 3, 4, 5].reduce(function (accum, value, index, array) {\n" \
"	return accum + value;\n" \
"}, 3);";
	static const gint targetOutput2 = 18;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	gint _tmp1_ = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gint _tmp4_ = 0;
	RubricWebMujsEngine* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp1_ = (gint) ((gintptr) _tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp1_;
	_tmp5_ = engine;
	_tmp6_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp5_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp4_ = (gint) ((gintptr) _tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp4_;
	_tmp7_ = output1;
	_vala_assert (targetOutput1 == _tmp7_, "targetOutput1 == output1");
	_tmp8_ = output2;
	_vala_assert (targetOutput2 == _tmp8_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_reduce_right_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input1[] = "[1, 2, 3, 4, 5].reduceRight(function (accum, value, index, array) {\n" \
"	return accum - value;\n" \
"});";
	static const gint targetOutput1 = -5;
	static const char input2[] = "[1, 2, 3, 4, 5].reduceRight(function (accum, value, index, array) {\n" \
"	return accum - value;\n" \
"}, 7);";
	static const gint targetOutput2 = -8;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	gint _tmp1_ = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gint _tmp4_ = 0;
	RubricWebMujsEngine* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp1_ = (gint) ((gintptr) _tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp1_;
	_tmp5_ = engine;
	_tmp6_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp5_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp4_ = (gint) ((gintptr) _tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp4_;
	_tmp7_ = output1;
	_vala_assert (targetOutput1 == _tmp7_, "targetOutput1 == output1");
	_tmp8_ = output2;
	_vala_assert (targetOutput2 == _tmp8_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_array_some_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var engines = ['Chakra', 'V8', 'SpiderMonkey', 'Jurassic'];";
	static const char input[] = "engines.some(function (value, index, array) { return value.length < 10" \
"; });";
	static const gboolean targetOutput = TRUE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean output = FALSE;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_BOOLEAN, NULL, NULL, input, NULL, &_inner_error_);
	_tmp2_ = (gboolean) ((gintptr) _tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output = _tmp2_;
	_tmp5_ = output;
	_vala_assert (targetOutput == _tmp5_, "targetOutput == output");
	_g_object_unref0 (engine);
}


static gdouble* _double_dup (gdouble* self) {
	gdouble* dup;
	dup = g_new0 (gdouble, 1);
	memcpy (dup, self, sizeof (gdouble));
	return dup;
}


static gchar* g_date_time_to_string (GDateTime* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_date_time_format (self, "%FT%H:%M:%S%z");
	result = _tmp0_;
	return result;
}


void _rubric_web_mujs_tests_es5_test_date_now_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input[] = "Date.now();";
	GDateTime* targetOutput = NULL;
	GDateTime* _tmp0_ = NULL;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	GDateTime* output = NULL;
	GDateTime* _tmp2_ = NULL;
	gdouble* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	GDateTime* _tmp5_ = NULL;
	gdouble _tmp6_ = 0.0;
	GDateTime* _tmp7_ = NULL;
	GDateTime* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	GDateTime* _tmp11_ = NULL;
	GTimeSpan _tmp12_ = 0LL;
	gdouble _tmp13_ = 0.0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_utc ();
	targetOutput = _tmp0_;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = g_date_time_new_utc (1970, 01, 01, 0, 0, (gdouble) 0);
	output = _tmp2_;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp3_ = (gdouble*) _tmp4_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_date_time_unref0 (output);
		_g_object_unref0 (engine);
		_g_date_time_unref0 (targetOutput);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = output;
	_tmp6_ = fabs (*_tmp3_);
	_tmp7_ = g_date_time_add_seconds (_tmp5_, _tmp6_);
	_g_date_time_unref0 (output);
	output = _tmp7_;
	_tmp8_ = output;
	_tmp9_ = g_date_time_to_string (_tmp8_);
	_tmp10_ = _tmp9_;
	g_debug ("es-5.vala:321: %s", _tmp10_);
	_g_free0 (_tmp10_);
	_tmp11_ = output;
	_tmp12_ = g_date_time_difference (targetOutput, _tmp11_);
	_tmp13_ = fabs ((gdouble) _tmp12_);
	_vala_assert (_tmp13_ < ((gdouble) 1000), "Math.fabs(targetOutput.difference(output)) < 1000");
	_g_free0 (_tmp3_);
	_g_date_time_unref0 (output);
	_g_object_unref0 (engine);
	_g_date_time_unref0 (targetOutput);
}


void rubric_web_mujs_tests_es5_test_date_to_iso_string_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input[] = "(new Date(1386696984000)).toISOString();";
	static const char targetOutput[] = "2013-12-10T17:36:24.000Z";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp1_ = (gchar*) _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = _tmp1_;
	_tmp1_ = NULL;
	_g_free0 (output);
	output = _tmp3_;
	_tmp4_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp4_) == 0, "targetOutput == output");
	_g_free0 (_tmp1_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_function_bind_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var a = 5,\n" \
"	module = {\n" \
"		a: 12,\n" \
"		getA: function() { return this.a; }\n" \
"	},\n" \
"	getA = module.getA\n" \
"	;";
	static const char input1[] = "getA();";
	static const gint targetOutput1 = 5;
	static const char input2[] = "getA.bind(module)();";
	static const gint targetOutput2 = 12;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	RubricWebMujsEngine* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp2_ = (gint) ((gintptr) _tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp2_;
	_tmp6_ = engine;
	_tmp7_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp5_ = (gint) ((gintptr) _tmp7_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp5_;
	_tmp8_ = output1;
	_vala_assert (targetOutput1 == _tmp8_, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (targetOutput2 == _tmp9_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_json_parse_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var obj = JSON.parse('{ \"foo\": \"bar\" }');";
	static const char input[] = "obj.foo;";
	static const char targetOutput[] = "bar";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp2_ = (gchar*) _tmp4_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = _tmp2_;
	_tmp2_ = NULL;
	_g_free0 (output);
	output = _tmp5_;
	_tmp6_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp6_) == 0, "targetOutput == output");
	_g_free0 (_tmp2_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_json_stringify_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode[] = "var obj = new Object();\nobj['foo'] = 'bar';";
	static const char input[] = "JSON.stringify(obj);";
	static const char targetOutput[] = "{\"foo\":\"bar\"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, initCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp2_ = (gchar*) _tmp4_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = _tmp2_;
	_tmp2_ = NULL;
	_g_free0 (output);
	output = _tmp5_;
	_tmp6_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp6_) == 0, "targetOutput == output");
	_g_free0 (_tmp2_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_object_create_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char initCode1[] = "var obj1 = Object.create(null);";
	static const char input1[] = "obj1.prototype";
	RubricWebUndefined* targetOutput1 = NULL;
	RubricWebUndefined* _tmp0_ = NULL;
	static const char initCode2[] = "var obj2 = Object.create(Object.prototype);";
	static const char input2[] = "typeof obj2;";
	static const char targetOutput2[] = "object";
	static const char initCode3[] = "var greeter = {\n" \
"	id: 678,\n" \
"	name: 'stranger',\n" \
"	greet: function() {\n" \
"		return 'Hello, ' + this.name + '!';\n" \
"	}\n" \
"};\n" \
"\n" \
"var myGreeter = Object.create(greeter);\n" \
"greeter.name = 'Vasya'";
	static const char input3A[] = "myGreeter.id";
	static const char input3B[] = "myGreeter.greet()";
	static const gint targetOutput3A = 678;
	static const char targetOutput3B[] = "Hello, Vasya!";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	RubricWebUndefined* output1 = NULL;
	gchar* output2 = NULL;
	gint output3A = 0;
	gchar* output3B = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	RubricWebUndefined* _tmp3_ = NULL;
	RubricWebMujsEngine* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	RubricWebUndefined* _tmp6_ = NULL;
	RubricWebMujsEngine* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	RubricWebMujsEngine* _tmp9_ = NULL;
	gpointer _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	RubricWebMujsEngine* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	RubricWebMujsEngine* _tmp14_ = NULL;
	gpointer _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	RubricWebMujsEngine* _tmp17_ = NULL;
	gpointer _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	const gchar* _tmp22_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_undefined_value ();
	targetOutput1 = _tmp0_;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp2_, initCode1, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp4_ = engine;
	_tmp5_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp4_, RUBRIC_WEB_TYPE_UNDEFINED, (GBoxedCopyFunc) rubric_web_undefined_ref, (GDestroyNotify) rubric_web_undefined_unref, input1, NULL, &_inner_error_);
	_tmp3_ = (RubricWebUndefined*) _tmp5_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp6_ = _tmp3_;
	_tmp3_ = NULL;
	_rubric_web_undefined_unref0 (output1);
	output1 = _tmp6_;
	_tmp7_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp7_, initCode2, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_rubric_web_undefined_unref0 (_tmp3_);
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp9_ = engine;
	_tmp10_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp9_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input2, NULL, &_inner_error_);
	_tmp8_ = (gchar*) _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_rubric_web_undefined_unref0 (_tmp3_);
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = _tmp8_;
	_tmp8_ = NULL;
	_g_free0 (output2);
	output2 = _tmp11_;
	_tmp12_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp12_, initCode3, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp8_);
		_rubric_web_undefined_unref0 (_tmp3_);
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp14_ = engine;
	_tmp15_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp14_, G_TYPE_INT, NULL, NULL, input3A, NULL, &_inner_error_);
	_tmp13_ = (gint) ((gintptr) _tmp15_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp8_);
		_rubric_web_undefined_unref0 (_tmp3_);
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output3A = _tmp13_;
	_tmp17_ = engine;
	_tmp18_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp17_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input3B, NULL, &_inner_error_);
	_tmp16_ = (gchar*) _tmp18_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp8_);
		_rubric_web_undefined_unref0 (_tmp3_);
		_g_free0 (output3B);
		_g_free0 (output2);
		_rubric_web_undefined_unref0 (output1);
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (targetOutput1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp19_ = _tmp16_;
	_tmp16_ = NULL;
	_g_free0 (output3B);
	output3B = _tmp19_;
	_tmp20_ = output2;
	_vala_assert (g_strcmp0 (targetOutput2, _tmp20_) == 0, "targetOutput2 == output2");
	_tmp21_ = output3A;
	_vala_assert (targetOutput3A == _tmp21_, "targetOutput3A == output3A");
	_tmp22_ = output3B;
	_vala_assert (g_strcmp0 (targetOutput3B, _tmp22_) == 0, "targetOutput3B == output3B");
	_g_free0 (_tmp16_);
	_g_free0 (_tmp8_);
	_rubric_web_undefined_unref0 (_tmp3_);
	_g_free0 (output3B);
	_g_free0 (output2);
	_rubric_web_undefined_unref0 (output1);
	_g_object_unref0 (engine);
	_rubric_web_undefined_unref0 (targetOutput1);
}


void rubric_web_mujs_tests_es5_test_object_keys_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input1[] = "Object.keys(['a', 'b', 'c']).toString();";
	static const char targetOutput1[] = "0,1,2";
	static const char input2[] = "Object.keys({ 0: 'a', 1: 'b', 2: 'c' }).toString();";
	static const char targetOutput2[] = "0,1,2";
	static const char input3[] = "Object.keys({ 100: 'a', 2: 'b', 7: 'c' }).toString();";
	static const char targetOutput3[] = "100,2,7";
	static const char initCode4[] = "var myObj = function() { };\n" \
"myObj.prototype = { getFoo: { value: function () { return this.foo } }" \
" };;\n" \
"myObj.foo = 1;\n";
	static const char input4[] = "Object.keys(myObj).toString();";
	static const char targetOutput4[] = "foo";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output1 = NULL;
	gchar* output2 = NULL;
	gchar* output3 = NULL;
	gchar* output4 = NULL;
	gchar* _tmp1_ = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	RubricWebMujsEngine* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	RubricWebMujsEngine* _tmp10_ = NULL;
	gpointer _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	RubricWebMujsEngine* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	RubricWebMujsEngine* _tmp15_ = NULL;
	gpointer _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input1, NULL, &_inner_error_);
	_tmp1_ = (gchar*) _tmp3_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output4);
		_g_free0 (output3);
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp4_ = _tmp1_;
	_tmp1_ = NULL;
	_g_free0 (output1);
	output1 = _tmp4_;
	_tmp6_ = engine;
	_tmp7_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input2, NULL, &_inner_error_);
	_tmp5_ = (gchar*) _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp1_);
		_g_free0 (output4);
		_g_free0 (output3);
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = _tmp5_;
	_tmp5_ = NULL;
	_g_free0 (output2);
	output2 = _tmp8_;
	_tmp10_ = engine;
	_tmp11_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp10_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input3, NULL, &_inner_error_);
	_tmp9_ = (gchar*) _tmp11_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp5_);
		_g_free0 (_tmp1_);
		_g_free0 (output4);
		_g_free0 (output3);
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp12_ = _tmp9_;
	_tmp9_ = NULL;
	_g_free0 (output3);
	output3 = _tmp12_;
	_tmp13_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp13_, initCode4, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp9_);
		_g_free0 (_tmp5_);
		_g_free0 (_tmp1_);
		_g_free0 (output4);
		_g_free0 (output3);
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp15_ = engine;
	_tmp16_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp15_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input4, NULL, &_inner_error_);
	_tmp14_ = (gchar*) _tmp16_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (_tmp9_);
		_g_free0 (_tmp5_);
		_g_free0 (_tmp1_);
		_g_free0 (output4);
		_g_free0 (output3);
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp17_ = _tmp14_;
	_tmp14_ = NULL;
	_g_free0 (output4);
	output4 = _tmp17_;
	_tmp18_ = output1;
	_vala_assert (g_strcmp0 (targetOutput1, _tmp18_) == 0, "targetOutput1 == output1");
	_tmp19_ = output2;
	_vala_assert (g_strcmp0 (targetOutput2, _tmp19_) == 0, "targetOutput2 == output2");
	_tmp20_ = output3;
	_vala_assert (g_strcmp0 (targetOutput3, _tmp20_) == 0, "targetOutput3 == output3");
	_g_free0 (_tmp14_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp1_);
	_g_free0 (output4);
	_g_free0 (output3);
	_g_free0 (output2);
	_g_free0 (output1);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_string_split_method (RubricWebMujsTestsEs5* self) {
	static const char input1[] = "'aaaa'.split('a').length;";
	static const gint targetOutput1 = 5;
	static const char input2[] = "'|a|b|c|'.split('|').length";
	static const gint targetOutput2 = 5;
	static const char input3[] = "'1, 2, 3, 4'.split(/\\s*(,)\\s*/).length";
	static const gint targetOutput3 = 7;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gint output1 = 0;
	gint output2 = 0;
	gint output3 = 0;
	gint _tmp1_ = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gint _tmp4_ = 0;
	RubricWebMujsEngine* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gint _tmp7_ = 0;
	RubricWebMujsEngine* _tmp8_ = NULL;
	gpointer _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, input1, NULL, &_inner_error_);
	_tmp1_ = (gint) ((gintptr) _tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output1 = _tmp1_;
	_tmp5_ = engine;
	_tmp6_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp5_, G_TYPE_INT, NULL, NULL, input2, NULL, &_inner_error_);
	_tmp4_ = (gint) ((gintptr) _tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output2 = _tmp4_;
	_tmp8_ = engine;
	_tmp9_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp8_, G_TYPE_INT, NULL, NULL, input3, NULL, &_inner_error_);
	_tmp7_ = (gint) ((gintptr) _tmp9_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output3 = _tmp7_;
	_tmp10_ = output1;
	_vala_assert (targetOutput1 == _tmp10_, "targetOutput1 == output1");
	_tmp11_ = output2;
	_vala_assert (targetOutput2 == _tmp11_, "targetOutput2 == output2");
	_tmp12_ = output3;
	_vala_assert (targetOutput3 == _tmp12_, "targetOutput3 == output3");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_es5_test_string_trim_method_is_supported (RubricWebMujsTestsEs5* self) {
	static const char input[] = "'	foo '.trim();";
	static const char targetOutput[] = "foo";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp2_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	_tmp1_ = (gchar*) _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = _tmp1_;
	_tmp1_ = NULL;
	_g_free0 (output);
	output = _tmp3_;
	_tmp4_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp4_) == 0, "targetOutput == output");
	_g_free0 (_tmp1_);
	_g_free0 (output);
	_g_object_unref0 (engine);
}


RubricWebMujsTestsEs5* rubric_web_mujs_tests_es5_construct (GType object_type) {
	RubricWebMujsTestsEs5 * self = NULL;
	self = (RubricWebMujsTestsEs5*) valadate_framework_test_case_construct (object_type);
	return self;
}


RubricWebMujsTestsEs5* rubric_web_mujs_tests_es5_new (void) {
	return rubric_web_mujs_tests_es5_construct (RUBRIC_WEB_MUJS_TESTS_TYPE_ES5);
}


static void rubric_web_mujs_tests_es5_class_init (RubricWebMujsTestsEs5Class * klass) {
	rubric_web_mujs_tests_es5_parent_class = g_type_class_peek_parent (klass);
}


static void rubric_web_mujs_tests_es5_instance_init (RubricWebMujsTestsEs5 * self) {
}


GType rubric_web_mujs_tests_es5_get_type (void) {
	static volatile gsize rubric_web_mujs_tests_es5_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_web_mujs_tests_es5_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricWebMujsTestsEs5Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rubric_web_mujs_tests_es5_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RubricWebMujsTestsEs5), 0, (GInstanceInitFunc) rubric_web_mujs_tests_es5_instance_init, NULL };
		GType rubric_web_mujs_tests_es5_type_id;
		rubric_web_mujs_tests_es5_type_id = g_type_register_static (VALADATE_FRAMEWORK_TYPE_TEST_CASE, "RubricWebMujsTestsEs5", &g_define_type_info, 0);
		g_once_init_leave (&rubric_web_mujs_tests_es5_type_id__volatile, rubric_web_mujs_tests_es5_type_id);
	}
	return rubric_web_mujs_tests_es5_type_id__volatile;
}



