/* mujs.c generated by valac 0.34.7, the Vala compiler
 * generated from mujs.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libvaladate-1.0.h>
#include <libmujs.h>
#include <stdlib.h>
#include <string.h>
#include <rubric-web.h>
#include <float.h>
#include <math.h>


#define RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE (rubric_web_mujs_tests_mujs_engine_get_type ())
#define RUBRIC_WEB_MUJS_TESTS_MUJS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE, RubricWebMujsTestsMujsEngine))
#define RUBRIC_WEB_MUJS_TESTS_MUJS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE, RubricWebMujsTestsMujsEngineClass))
#define RUBRIC_WEB_MUJS_TESTS_IS_MUJS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE))
#define RUBRIC_WEB_MUJS_TESTS_IS_MUJS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE))
#define RUBRIC_WEB_MUJS_TESTS_MUJS_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE, RubricWebMujsTestsMujsEngineClass))

typedef struct _RubricWebMujsTestsMujsEngine RubricWebMujsTestsMujsEngine;
typedef struct _RubricWebMujsTestsMujsEngineClass RubricWebMujsTestsMujsEngineClass;
typedef struct _RubricWebMujsTestsMujsEnginePrivate RubricWebMujsTestsMujsEnginePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _rubric_web_undefined_unref0(var) ((var == NULL) ? NULL : (var = (rubric_web_undefined_unref (var), NULL)))
#define __vala_GValue_free0(var) ((var == NULL) ? NULL : (var = (_vala_GValue_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _RubricWebMujsTestsMujsEngine {
	ValadateFrameworkTestCase parent_instance;
	RubricWebMujsTestsMujsEnginePrivate * priv;
};

struct _RubricWebMujsTestsMujsEngineClass {
	ValadateFrameworkTestCaseClass parent_class;
};


static gpointer rubric_web_mujs_tests_mujs_engine_parent_class = NULL;

GType rubric_web_mujs_tests_mujs_engine_get_type (void) G_GNUC_CONST;
enum  {
	RUBRIC_WEB_MUJS_TESTS_MUJS_ENGINE_DUMMY_PROPERTY
};
void rubric_web_mujs_tests_mujs_engine_test_new_engine (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_null_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_bool_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_integer_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_double_result (RubricWebMujsTestsMujsEngine* self);
static gdouble* _double_dup (gdouble* self);
static gboolean _double_equal (const gdouble* s1, const gdouble* s2);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_eval_expression_unicode_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_execution_of_code (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_execution_of_file (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_without_parameters (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_undefined_result (RubricWebMujsTestsMujsEngine* self);
static void _vala_GValue_free (GValue* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_null_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_boolean_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_integer_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_double_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_unicode_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_boolean_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_integer_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_double_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_unicode_string_result (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_undefined (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_null (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_boolean (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_integer (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_double (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_string (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_unicode_string (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_removing_variable (RubricWebMujsTestsMujsEngine* self);
void _rubric_web_mujs_tests_mujs_engine_test_garbage_collection (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_mapping_error_during_evaluation_of_expression (RubricWebMujsTestsMujsEngine* self);
void rubric_web_mujs_tests_mujs_engine_test_mapping_error_during_execution_of_code (RubricWebMujsTestsMujsEngine* self);
RubricWebMujsTestsMujsEngine* rubric_web_mujs_tests_mujs_engine_new (void);
RubricWebMujsTestsMujsEngine* rubric_web_mujs_tests_mujs_engine_construct (GType object_type);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


void rubric_web_mujs_tests_mujs_engine_test_new_engine (RubricWebMujsTestsMujsEngine* self) {
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_vala_assert (G_TYPE_CHECK_INSTANCE_TYPE (engine, RUBRIC_WEB_MUJS_TYPE_ENGINE), "engine is RubricWeb.Mujs.Engine");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_null_result (RubricWebMujsTestsMujsEngine* self) {
	gchar* input = NULL;
	gchar* _tmp0_ = NULL;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	void* output = NULL;
	gpointer _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("null");
	input = _tmp0_;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_POINTER, NULL, NULL, input, NULL, &_inner_error_);
	output = _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (input);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (output == NULL, "output == null");
	_g_object_unref0 (engine);
	_g_free0 (input);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_bool_result (RubricWebMujsTestsMujsEngine* self) {
	gchar* input1 = NULL;
	gchar* _tmp0_ = NULL;
	gboolean targetOutput1 = FALSE;
	gchar* input2 = NULL;
	gchar* _tmp1_ = NULL;
	gboolean targetOutput2 = FALSE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gboolean output1 = FALSE;
	RubricWebMujsEngine* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	gboolean output2 = FALSE;
	RubricWebMujsEngine* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gpointer _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	gboolean _tmp12_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("7 > 5");
	input1 = _tmp0_;
	targetOutput1 = TRUE;
	_tmp1_ = g_strdup ("null === undefined");
	input2 = _tmp1_;
	targetOutput2 = FALSE;
	_tmp2_ = rubric_web_mujs_engine_new ();
	engine = _tmp2_;
	_tmp3_ = engine;
	_tmp4_ = input1;
	_tmp5_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp3_, G_TYPE_BOOLEAN, NULL, NULL, _tmp4_, NULL, &_inner_error_);
	output1 = (gboolean) ((gintptr) _tmp5_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (input2);
		_g_free0 (input1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp6_ = engine;
	_tmp7_ = input2;
	_tmp8_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp6_, G_TYPE_BOOLEAN, NULL, NULL, _tmp7_, NULL, &_inner_error_);
	output2 = (gboolean) ((gintptr) _tmp8_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (input2);
		_g_free0 (input1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp9_ = targetOutput1;
	_tmp10_ = output1;
	_vala_assert (_tmp9_ == _tmp10_, "targetOutput1 == output1");
	_tmp11_ = targetOutput2;
	_tmp12_ = output2;
	_vala_assert (_tmp11_ == _tmp12_, "targetOutput2 == output2");
	_g_object_unref0 (engine);
	_g_free0 (input2);
	_g_free0 (input1);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_integer_result (RubricWebMujsTestsMujsEngine* self) {
	gchar* input = NULL;
	gchar* _tmp0_ = NULL;
	gint targetOutput = 0;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint output = 0;
	gpointer _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("7 * 8 - 20");
	input = _tmp0_;
	targetOutput = 36;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_INT, NULL, NULL, input, NULL, &_inner_error_);
	output = (gint) ((gintptr) _tmp2_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (input);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (targetOutput == output, "targetOutput == output");
	_g_object_unref0 (engine);
	_g_free0 (input);
}


static gdouble* _double_dup (gdouble* self) {
	gdouble* dup;
	dup = g_new0 (gdouble, 1);
	memcpy (dup, self, sizeof (gdouble));
	return dup;
}


static gboolean _double_equal (const gdouble* s1, const gdouble* s2) {
	if (s1 == s2) {
		return TRUE;
	}
	if (s1 == NULL) {
		return FALSE;
	}
	if (s2 == NULL) {
		return FALSE;
	}
	return (*s1) == (*s2);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_double_result (RubricWebMujsTestsMujsEngine* self) {
	gchar* input = NULL;
	gchar* _tmp0_ = NULL;
	gdouble targetOutput = 0.0;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gdouble* output = NULL;
	gpointer _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("Math.PI + 0.22");
	input = _tmp0_;
	targetOutput = G_PI + 0.22;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	output = (gdouble*) _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (input);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (_double_equal (&targetOutput, output) == TRUE, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
	_g_free0 (input);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char input[] = "'Hello, ' + \"Sup\" + '?';";
	static const char targetOutput[] = "Hello, Sup?";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	gpointer _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	output = (gchar*) _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (g_strcmp0 (targetOutput, output) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_eval_expression_unicode_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char input[] = "'Привет, ' + \"Вася\" + '?';";
	static const char targetOutput[] = "Привет, Вася?";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gchar* output = NULL;
	gpointer _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, input, NULL, &_inner_error_);
	output = (gchar*) _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (g_strcmp0 (targetOutput, output) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_execution_of_code (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function add(num1, num2) {\n				return (num1 + num2);\n			}";
	static const char input[] = "add(7, 9);";
	static const gint targetOutput = 16;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint output = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, input, NULL, &_inner_error_);
	output = (gint) ((gintptr) _tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp4_ = output;
	_vala_assert (targetOutput == _tmp4_, "targetOutput == output");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_execution_of_file (RubricWebMujsTestsMujsEngine* self) {
	gchar* filePath = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	static const char input[] = "square(6);";
	static const gint targetOutput = 36;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gint output = 0;
	RubricWebMujsEngine* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gint _tmp7_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_getenv ("srcdir");
	_tmp1_ = g_strconcat (_tmp0_, "/data/square.js", NULL);
	filePath = _tmp1_;
	_tmp2_ = rubric_web_mujs_engine_new ();
	engine = _tmp2_;
	_tmp3_ = engine;
	_tmp4_ = filePath;
	rubric_web_js_engine_execute_file ((RubricWebJSEngine*) _tmp3_, _tmp4_, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (filePath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = engine;
	_tmp6_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) _tmp5_, G_TYPE_INT, NULL, NULL, input, NULL, &_inner_error_);
	output = (gint) ((gintptr) _tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_g_free0 (filePath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp7_ = output;
	_vala_assert (targetOutput == _tmp7_, "targetOutput == output");
	_g_object_unref0 (engine);
	_g_free0 (filePath);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_without_parameters (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function hooray() {\n	return 'Hooray!';\n}";
	static const char targetOutput[] = "Hooray!";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "hooray", NULL, 0, NULL, &_inner_error_);
	output = (gchar*) _tmp3_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp4_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp4_) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


static void _vala_GValue_free (GValue* self) {
	g_value_unset (self);
	g_free (self);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_undefined_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function testUndefined(value) {\n" \
"	if (typeof value !== 'undefined') {\n" \
"		throw new TypeError();\n" \
"	}\n" \
"	return undefined;\n" \
"}";
	RubricWebUndefined* input = NULL;
	RubricWebUndefined* _tmp0_ = NULL;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	RubricWebUndefined* output = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	RubricWebUndefined* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue** _tmp6_ = NULL;
	GValue** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	gpointer _tmp8_ = NULL;
	RubricWebUndefined* _tmp9_ = NULL;
	RubricWebUndefined* _tmp10_ = NULL;
	RubricWebUndefined* _tmp11_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_undefined_value ();
	input = _tmp0_;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp2_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (input);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = input;
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, RUBRIC_WEB_TYPE_UNDEFINED);
	rubric_web_value_set_undefined (_tmp5_, _tmp4_);
	_tmp6_ = g_new0 (GValue*, 1);
	_tmp6_[0] = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp7__length1 = 1;
	_tmp8_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp3_, RUBRIC_WEB_TYPE_UNDEFINED, (GBoxedCopyFunc) rubric_web_undefined_ref, (GDestroyNotify) rubric_web_undefined_unref, "testUndefined", _tmp7_, 1, NULL, &_inner_error_);
	_tmp9_ = (RubricWebUndefined*) _tmp8_;
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp9_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		_rubric_web_undefined_unref0 (input);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp10_ = input;
	_tmp11_ = output;
	_vala_assert (_tmp10_ == _tmp11_, "input == output");
	_rubric_web_undefined_unref0 (output);
	_g_object_unref0 (engine);
	_rubric_web_undefined_unref0 (input);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_null_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function testNull(value) {\n" \
"	if (value !== null) {\n" \
"		throw new TypeError();\n" \
"	}\n" \
"	return null;\n" \
"}";
	void* input = NULL;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	void* output = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	GValue** _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gpointer _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	input = NULL;
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = g_new0 (GValue*, 1);
	_tmp4_[0] = NULL;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp3_, G_TYPE_POINTER, NULL, NULL, "testNull", _tmp5_, 1, NULL, &_inner_error_);
	_tmp7_ = _tmp6_;
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	_tmp2_ = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	output = _tmp2_;
	_tmp8_ = output;
	_vala_assert (_tmp8_ == NULL, "output == null");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_boolean_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function inverse(value) {\n	return !value;\n}";
	static const gboolean input = FALSE;
	static const gboolean targetOutput = TRUE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gboolean output = FALSE;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue** _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gpointer _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	gboolean _tmp8_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp3_, input);
	_tmp4_ = g_new0 (GValue*, 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_BOOLEAN, NULL, NULL, "inverse", _tmp5_, 1, NULL, &_inner_error_);
	_tmp7_ = (gboolean) ((gintptr) _tmp6_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = output;
	_vala_assert (targetOutput == _tmp8_, "targetOutput == output");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_integer_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function negate(value) {\n	return -1 * value;\n}";
	static const gint input = 28;
	static const gint targetOutput = -28;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint output = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue** _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gpointer _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_INT);
	g_value_set_int (_tmp3_, input);
	_tmp4_ = g_new0 (GValue*, 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, "negate", _tmp5_, 1, NULL, &_inner_error_);
	_tmp7_ = (gint) ((gintptr) _tmp6_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = output;
	_vala_assert (targetOutput == _tmp8_, "targetOutput == output");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_double_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function triple(value) {\n	return 3 * value;\n}";
	static const gdouble input = 3.2;
	static const gdouble targetOutput = 9.6;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gdouble* _tmp2_ = NULL;
	RubricWebMujsEngine* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	GValue** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	gpointer _tmp7_ = NULL;
	gdouble* _tmp8_ = NULL;
	gdouble output = 0.0;
	gdouble _tmp9_ = 0.0;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gdouble _tmp12_ = 0.0;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = engine;
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp4_, input);
	_tmp5_ = g_new0 (GValue*, 1);
	_tmp5_[0] = _tmp4_;
	_tmp6_ = _tmp5_;
	_tmp6__length1 = 1;
	_tmp7_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp3_, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, "triple", _tmp6_, 1, NULL, &_inner_error_);
	_tmp8_ = (gdouble*) _tmp7_;
	_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	_tmp2_ = _tmp8_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp9_ = round (*_tmp2_);
	output = _tmp9_;
	_tmp10_ = g_strdup_printf ("%1.0f", targetOutput);
	_tmp11_ = _tmp10_;
	_tmp12_ = output;
	_tmp13_ = g_strdup_printf ("%1.0f", _tmp12_);
	_tmp14_ = _tmp13_;
	_vala_assert (g_strcmp0 (_tmp11_, _tmp14_) == 0, "\"%1.0f\".printf(targetOutput) == \"%1.0f\".printf(output)");
	_g_free0 (_tmp14_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp2_);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function greeting(name) {\n	return 'Hello, ' + name + '!';\n}";
	static const char input[] = "Vovan";
	static const char targetOutput[] = "Hello, Vovan!";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue** _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gpointer _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_STRING);
	g_value_set_string (_tmp3_, input);
	_tmp4_ = g_new0 (GValue*, 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "greeting", _tmp5_, 1, NULL, &_inner_error_);
	_tmp7_ = (gchar*) _tmp6_;
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp8_) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_unicode_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function privet(name) {\n	return 'Привет, ' + name + '!';\n}";
	static const char input[] = "Вован";
	static const char targetOutput[] = "Привет, Вован!";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue** _tmp4_ = NULL;
	GValue** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gpointer _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_STRING);
	g_value_set_string (_tmp3_, input);
	_tmp4_ = g_new0 (GValue*, 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "privet", _tmp5_, 1, NULL, &_inner_error_);
	_tmp7_ = (gchar*) _tmp6_;
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = output;
	_vala_assert (g_strcmp0 (targetOutput, _tmp8_) == 0, "targetOutput == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function determineArgumentsTypes() {\n" \
"	var result = '',\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		if (argumentIndex > 0) {\n" \
"			result += ', ';\n" \
"		}\n" \
"		result += typeof arguments[argumentIndex];\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	RubricWebUndefined* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue* _tmp7_ = NULL;
	GValue* _tmp8_ = NULL;
	GValue** _tmp9_ = NULL;
	GValue** _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	gpointer _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = rubric_web_undefined_value ();
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, RUBRIC_WEB_TYPE_UNDEFINED);
	rubric_web_value_take_undefined (_tmp4_, _tmp3_);
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp5_, TRUE);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_INT);
	g_value_set_int (_tmp6_, 12);
	_tmp7_ = g_new0 (GValue, 1);
	g_value_init (_tmp7_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp7_, 3.14);
	_tmp8_ = g_new0 (GValue, 1);
	g_value_init (_tmp8_, G_TYPE_STRING);
	g_value_set_string (_tmp8_, "test");
	_tmp9_ = g_new0 (GValue*, 6);
	_tmp9_[0] = _tmp4_;
	_tmp9_[1] = NULL;
	_tmp9_[2] = _tmp5_;
	_tmp9_[3] = _tmp6_;
	_tmp9_[4] = _tmp7_;
	_tmp9_[5] = _tmp8_;
	_tmp10_ = _tmp9_;
	_tmp10__length1 = 6;
	_tmp11_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "determineArgumentsTypes", _tmp10_, 6, NULL, &_inner_error_);
	_tmp12_ = (gchar*) _tmp11_;
	_tmp10_ = (_vala_array_free (_tmp10_, _tmp10__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp12_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp13_ = output;
	_vala_assert (g_strcmp0 ("undefined, object, boolean, number, number, string", _tmp13_) == 0, "\"undefined, object, boolean, number, number, string\" == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_boolean_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function and() {\n" \
"	var result = null,\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length,\n" \
"		argumentValue\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		argumentValue = arguments[argumentIndex];\n" \
"		if (result !== null) {\n" \
"			result = result && argumentValue;\n" \
"		}\n" \
"		else {\n" \
"			result = argumentValue;\n" \
"		}\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gboolean output = FALSE;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue** _tmp7_ = NULL;
	GValue** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gpointer _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp3_, TRUE);
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp4_, TRUE);
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp5_, FALSE);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp6_, TRUE);
	_tmp7_ = g_new0 (GValue*, 4);
	_tmp7_[0] = _tmp3_;
	_tmp7_[1] = _tmp4_;
	_tmp7_[2] = _tmp5_;
	_tmp7_[3] = _tmp6_;
	_tmp8_ = _tmp7_;
	_tmp8__length1 = 4;
	_tmp9_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_BOOLEAN, NULL, NULL, "and", _tmp8_, 4, NULL, &_inner_error_);
	_tmp10_ = (gboolean) ((gintptr) _tmp9_);
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = output;
	_vala_assert (FALSE == _tmp11_, "false == output");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_integer_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function sum() {\n" \
"	var result = 0,\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		result += arguments[argumentIndex];\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gint output = 0;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue** _tmp7_ = NULL;
	GValue** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gpointer _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_INT);
	g_value_set_int (_tmp3_, 120);
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_INT);
	g_value_set_int (_tmp4_, 5);
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_INT);
	g_value_set_int (_tmp5_, 18);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_INT);
	g_value_set_int (_tmp6_, 63);
	_tmp7_ = g_new0 (GValue*, 4);
	_tmp7_[0] = _tmp3_;
	_tmp7_[1] = _tmp4_;
	_tmp7_[2] = _tmp5_;
	_tmp7_[3] = _tmp6_;
	_tmp8_ = _tmp7_;
	_tmp8__length1 = 4;
	_tmp9_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_INT, NULL, NULL, "sum", _tmp8_, 4, NULL, &_inner_error_);
	_tmp10_ = (gint) ((gintptr) _tmp9_);
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = output;
	_vala_assert (206 == _tmp11_, "206 == output");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_double_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function sum() {\n" \
"	var result = 0,\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		result += arguments[argumentIndex];\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gdouble* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue** _tmp7_ = NULL;
	GValue** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gpointer _tmp9_ = NULL;
	gdouble* _tmp10_ = NULL;
	gdouble _tmp11_ = 0.0;
	gdouble* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_INT);
	g_value_set_int (_tmp3_, 22000);
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp4_, 8.5);
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp5_, 0.05);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_INT);
	g_value_set_int (_tmp6_, 3);
	_tmp7_ = g_new0 (GValue*, 4);
	_tmp7_[0] = _tmp3_;
	_tmp7_[1] = _tmp4_;
	_tmp7_[2] = _tmp5_;
	_tmp7_[3] = _tmp6_;
	_tmp8_ = _tmp7_;
	_tmp8__length1 = 4;
	_tmp9_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, "sum", _tmp8_, 4, NULL, &_inner_error_);
	_tmp10_ = (gdouble*) _tmp9_;
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = 22011.55;
	_tmp12_ = output;
	_vala_assert (_double_equal (&_tmp11_, _tmp12_) == TRUE, "22011.55 == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function concatenate() {\n" \
"	var result = '',\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		result += arguments[argumentIndex];\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue* _tmp7_ = NULL;
	GValue** _tmp8_ = NULL;
	GValue** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gpointer _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_STRING);
	g_value_set_string (_tmp3_, "Hello");
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_STRING);
	g_value_set_string (_tmp4_, ",");
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_STRING);
	g_value_set_string (_tmp5_, " ");
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_STRING);
	g_value_set_string (_tmp6_, "Petya");
	_tmp7_ = g_new0 (GValue, 1);
	g_value_init (_tmp7_, G_TYPE_STRING);
	g_value_set_string (_tmp7_, "!");
	_tmp8_ = g_new0 (GValue*, 5);
	_tmp8_[0] = _tmp3_;
	_tmp8_[1] = _tmp4_;
	_tmp8_[2] = _tmp5_;
	_tmp8_[3] = _tmp6_;
	_tmp8_[4] = _tmp7_;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 5;
	_tmp10_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "concatenate", _tmp9_, 5, NULL, &_inner_error_);
	_tmp11_ = (gchar*) _tmp10_;
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp11_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp12_ = output;
	_vala_assert (g_strcmp0 ("Hello, Petya!", _tmp12_) == 0, "\"Hello, Petya!\" == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_calling_of_function_with_many_parameters_and_unicode_string_result (RubricWebMujsTestsMujsEngine* self) {
	static const char functionCode[] = "function obedinit() {\n" \
"	var result = '',\n" \
"		argumentIndex,\n" \
"		argumentCount = arguments.length\n" \
"		;\n" \
"	for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex+" \
"+) {\n" \
"		result += arguments[argumentIndex];\n" \
"	}\n" \
"	return result;\n" \
"}";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gchar* output = NULL;
	RubricWebMujsEngine* _tmp2_ = NULL;
	GValue* _tmp3_ = NULL;
	GValue* _tmp4_ = NULL;
	GValue* _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	GValue* _tmp7_ = NULL;
	GValue** _tmp8_ = NULL;
	GValue** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gpointer _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = engine;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) _tmp1_, functionCode, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = engine;
	_tmp3_ = g_new0 (GValue, 1);
	g_value_init (_tmp3_, G_TYPE_STRING);
	g_value_set_string (_tmp3_, "Привет");
	_tmp4_ = g_new0 (GValue, 1);
	g_value_init (_tmp4_, G_TYPE_STRING);
	g_value_set_string (_tmp4_, ",");
	_tmp5_ = g_new0 (GValue, 1);
	g_value_init (_tmp5_, G_TYPE_STRING);
	g_value_set_string (_tmp5_, " ");
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_STRING);
	g_value_set_string (_tmp6_, "Петя");
	_tmp7_ = g_new0 (GValue, 1);
	g_value_init (_tmp7_, G_TYPE_STRING);
	g_value_set_string (_tmp7_, "!");
	_tmp8_ = g_new0 (GValue*, 5);
	_tmp8_[0] = _tmp3_;
	_tmp8_[1] = _tmp4_;
	_tmp8_[2] = _tmp5_;
	_tmp8_[3] = _tmp6_;
	_tmp8_[4] = _tmp7_;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 5;
	_tmp10_ = rubric_web_js_engine_call_function ((RubricWebJSEngine*) _tmp2_, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, "obedinit", _tmp9_, 5, NULL, &_inner_error_);
	_tmp11_ = (gchar*) _tmp10_;
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) _vala_GValue_free), NULL);
	output = _tmp11_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp12_ = output;
	_vala_assert (g_strcmp0 ("Привет, Петя!", _tmp12_) == 0, "\"\320\237\321\200\320\270\320\262\320\265\321\202, \320\237\320\265\321\202\321\217!\" == output");
	_g_free0 (output);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_undefined (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "myVar1";
	RubricWebUndefined* input = NULL;
	RubricWebUndefined* _tmp0_ = NULL;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp1_ = NULL;
	gboolean variableExists = FALSE;
	GValue* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	RubricWebUndefined* output = NULL;
	gpointer _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_undefined_value ();
	input = _tmp0_;
	_tmp1_ = rubric_web_mujs_engine_new ();
	engine = _tmp1_;
	_tmp2_ = g_new0 (GValue, 1);
	g_value_init (_tmp2_, RUBRIC_WEB_TYPE_UNDEFINED);
	rubric_web_value_set_undefined (_tmp2_, input);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp2_);
	__vala_GValue_free0 (_tmp2_);
	_tmp3_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp3_;
	_tmp4_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, RUBRIC_WEB_TYPE_UNDEFINED, (GBoxedCopyFunc) rubric_web_undefined_ref, (GDestroyNotify) rubric_web_undefined_unref, variableName);
	output = (RubricWebUndefined*) _tmp4_;
	_vala_assert (!variableExists, "!variableExists");
	_vala_assert (input == output, "input == output");
	_rubric_web_undefined_unref0 (output);
	_g_object_unref0 (engine);
	_rubric_web_undefined_unref0 (input);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_null (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "myVar2";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gboolean _tmp1_ = FALSE;
	void* output = NULL;
	gpointer _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, NULL);
	_tmp1_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp1_;
	_tmp2_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_POINTER, NULL, NULL, variableName);
	output = _tmp2_;
	_vala_assert (variableExists, "variableExists");
	_vala_assert (output == NULL, "output == null");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_boolean (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "isVisible";
	static const gboolean input1 = TRUE;
	static const gboolean targetOutput1 = FALSE;
	static const gboolean input2 = TRUE;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gboolean output1 = FALSE;
	gboolean output2 = FALSE;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp1_, input1);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp2_;
	_tmp3_ = g_strdup_printf ("%s = !%s;", variableName, variableName);
	_tmp4_ = _tmp3_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	_g_free0 (_tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_BOOLEAN, NULL, NULL, variableName);
	output1 = (gboolean) ((gintptr) _tmp5_);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_BOOLEAN);
	g_value_set_boolean (_tmp6_, input2);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp6_);
	__vala_GValue_free0 (_tmp6_);
	_tmp7_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_BOOLEAN, NULL, NULL, variableName);
	output2 = (gboolean) ((gintptr) _tmp7_);
	_vala_assert (variableExists, "variableExists");
	_tmp8_ = output1;
	_vala_assert (targetOutput1 == _tmp8_, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (input2 == _tmp9_, "input2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_integer (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "amount";
	static const gint input1 = 38;
	static const gint targetOutput1 = 41;
	static const gint input2 = 711;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gint output1 = 0;
	gint output2 = 0;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_INT);
	g_value_set_int (_tmp1_, input1);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp2_;
	_tmp3_ = g_strdup_printf ("%s += 3;", variableName);
	_tmp4_ = _tmp3_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	_g_free0 (_tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_INT, NULL, NULL, variableName);
	output1 = (gint) ((gintptr) _tmp5_);
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_INT);
	g_value_set_int (_tmp6_, input2);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp6_);
	__vala_GValue_free0 (_tmp6_);
	_tmp7_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_INT, NULL, NULL, variableName);
	output2 = (gint) ((gintptr) _tmp7_);
	_vala_assert (variableExists, "variableExists");
	_tmp8_ = output1;
	_vala_assert (targetOutput1 == _tmp8_, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (input2 == _tmp9_, "input2 == output2");
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_double (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "price";
	static const gdouble input1 = 2.20;
	static const gdouble targetOutput1 = 2.17;
	static const gdouble input2 = 3.50;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gchar* output1 = NULL;
	gchar* output2 = NULL;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	gdouble* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GValue* _tmp8_ = NULL;
	gpointer _tmp9_ = NULL;
	gdouble* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp1_, input1);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp2_;
	_tmp3_ = g_strdup_printf ("%s -= 0.03;", variableName);
	_tmp4_ = _tmp3_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	_g_free0 (_tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, variableName);
	_tmp6_ = (gdouble*) _tmp5_;
	_tmp7_ = g_strdup_printf ("%1.2f", *_tmp6_);
	_g_free0 (output1);
	output1 = _tmp7_;
	_g_free0 (_tmp6_);
	_tmp8_ = g_new0 (GValue, 1);
	g_value_init (_tmp8_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp8_, input2);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp8_);
	__vala_GValue_free0 (_tmp8_);
	_tmp9_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_DOUBLE, (GBoxedCopyFunc) _double_dup, (GDestroyNotify) g_free, variableName);
	_tmp10_ = (gdouble*) _tmp9_;
	_tmp11_ = g_strdup_printf ("%1.2f", *_tmp10_);
	_g_free0 (output2);
	output2 = _tmp11_;
	_g_free0 (_tmp10_);
	_vala_assert (variableExists, "variableExists");
	_tmp12_ = g_strdup_printf ("%1.2f", targetOutput1);
	_tmp13_ = _tmp12_;
	_tmp14_ = output1;
	_vala_assert (g_strcmp0 (_tmp13_, _tmp14_) == 0, "\"%1.2f\".printf(targetOutput1) == output1");
	_g_free0 (_tmp13_);
	_tmp15_ = g_strdup_printf ("%1.2f", input2);
	_tmp16_ = _tmp15_;
	_tmp17_ = output2;
	_vala_assert (g_strcmp0 (_tmp16_, _tmp17_) == 0, "\"%1.2f\".printf(input2) == output2");
	_g_free0 (_tmp16_);
	_g_free0 (output2);
	_g_free0 (output1);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_string (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "word";
	static const char input1[] = "Hooray";
	static const char targetOutput1[] = "Hooray!";
	static const char input2[] = "Hurrah";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gchar* output1 = NULL;
	gchar* output2 = NULL;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_STRING);
	g_value_set_string (_tmp1_, input1);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp2_;
	_tmp3_ = g_strdup_printf ("%s += '!';", variableName);
	_tmp4_ = _tmp3_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	_g_free0 (_tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, variableName);
	_g_free0 (output1);
	output1 = (gchar*) _tmp5_;
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_STRING);
	g_value_set_string (_tmp6_, input2);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp6_);
	__vala_GValue_free0 (_tmp6_);
	_tmp7_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, variableName);
	_g_free0 (output2);
	output2 = (gchar*) _tmp7_;
	_vala_assert (variableExists, "variableExists");
	_tmp8_ = output1;
	_vala_assert (g_strcmp0 (targetOutput1, _tmp8_) == 0, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (g_strcmp0 (input2, _tmp9_) == 0, "input2 == output2");
	_g_free0 (output2);
	_g_free0 (output1);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_setting_and_getting_variable_with_unicode_string (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "slovo";
	static const char input1[] = "Ура";
	static const char targetOutput1[] = "Ура!";
	static const char input2[] = "Урааа";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableExists = FALSE;
	gchar* output1 = NULL;
	gchar* output2 = NULL;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	GValue* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_STRING);
	g_value_set_string (_tmp1_, input1);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableExists = _tmp2_;
	_tmp3_ = g_strdup_printf ("%s += '!';", variableName);
	_tmp4_ = _tmp3_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, _tmp4_, NULL, &_inner_error_);
	_g_free0 (_tmp4_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (output2);
		_g_free0 (output1);
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, variableName);
	_g_free0 (output1);
	output1 = (gchar*) _tmp5_;
	_tmp6_ = g_new0 (GValue, 1);
	g_value_init (_tmp6_, G_TYPE_STRING);
	g_value_set_string (_tmp6_, input2);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp6_);
	__vala_GValue_free0 (_tmp6_);
	_tmp7_ = rubric_web_js_engine_get_variable ((RubricWebJSEngine*) engine, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, variableName);
	_g_free0 (output2);
	output2 = (gchar*) _tmp7_;
	_vala_assert (variableExists, "variableExists");
	_tmp8_ = output1;
	_vala_assert (g_strcmp0 (targetOutput1, _tmp8_) == 0, "targetOutput1 == output1");
	_tmp9_ = output2;
	_vala_assert (g_strcmp0 (input2, _tmp9_) == 0, "input2 == output2");
	_g_free0 (output2);
	_g_free0 (output1);
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_removing_variable (RubricWebMujsTestsMujsEngine* self) {
	static const char variableName[] = "price";
	static const gdouble input = 120.55;
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean variableBeforeRemovingExists = FALSE;
	gboolean variableAfterRemovingExists = FALSE;
	GValue* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	_tmp1_ = g_new0 (GValue, 1);
	g_value_init (_tmp1_, G_TYPE_DOUBLE);
	g_value_set_double (_tmp1_, input);
	rubric_web_js_engine_set_variable ((RubricWebJSEngine*) engine, variableName, _tmp1_);
	__vala_GValue_free0 (_tmp1_);
	_tmp2_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableBeforeRemovingExists = _tmp2_;
	rubric_web_js_engine_remove_variable ((RubricWebJSEngine*) engine, variableName);
	_tmp3_ = rubric_web_js_engine_has_variable ((RubricWebJSEngine*) engine, variableName);
	variableAfterRemovingExists = _tmp3_;
	_vala_assert (variableBeforeRemovingExists, "variableBeforeRemovingExists");
	_vala_assert (!variableAfterRemovingExists, "!variableAfterRemovingExists");
	_g_object_unref0 (engine);
}


void _rubric_web_mujs_tests_mujs_engine_test_garbage_collection (RubricWebMujsTestsMujsEngine* self) {
	static const char input[] = "arr = []; for (i = 0; i < 1000000; i++) { arr.push(arr); }";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, input, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp1_ = rubric_web_js_engine_get_supports_gc ((RubricWebJSEngine*) engine);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		rubric_web_js_engine_collect_garbage ((RubricWebJSEngine*) engine);
	}
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_mapping_error_during_evaluation_of_expression (RubricWebMujsTestsMujsEngine* self) {
	static const char input[] = "var $variable1 = 611;\n" \
"var _variable2 = 711;\n" \
"var @variable3 = 678;\n" \
"$variable1 + _variable2 - variable3;";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	{
		gint _result_ = 0;
		gpointer _tmp1_ = NULL;
		_tmp1_ = rubric_web_js_engine_evaluate ((RubricWebJSEngine*) engine, G_TYPE_INT, NULL, NULL, input, NULL, &_inner_error_);
		_result_ = (gint) ((gintptr) _tmp1_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == RUBRIC_WEB_ENGINE_ERROR) {
				goto __catch0_rubric_web_engine_error;
			}
			_g_object_unref0 (engine);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally0;
	__catch0_rubric_web_engine_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (engine);
}


void rubric_web_mujs_tests_mujs_engine_test_mapping_error_during_execution_of_code (RubricWebMujsTestsMujsEngine* self) {
	static const char input[] = "function factorial(value) {\n" \
"\tif (value <= 0) {\n" \
"\t\tthrow new Error(\"\"The value must be greater than or equal to zer" \
"o.\"\");\n" \
"\t}\n" \
"\treturn value !== 1 ? value * factorial(value - 1) : 1;\n" \
"}\n" \
"factorial(5);\n" \
"factorial(@);\n" \
"factorial(0);";
	RubricWebMujsEngine* engine = NULL;
	RubricWebMujsEngine* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = rubric_web_mujs_engine_new ();
	engine = _tmp0_;
	{
		rubric_web_js_engine_execute ((RubricWebJSEngine*) engine, input, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == RUBRIC_WEB_ENGINE_ERROR) {
				goto __catch1_rubric_web_engine_error;
			}
			_g_object_unref0 (engine);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		g_assert_not_reached ();
	}
	goto __finally1;
	__catch1_rubric_web_engine_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_g_error_free0 (e);
	}
	__finally1:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (engine);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (engine);
}


RubricWebMujsTestsMujsEngine* rubric_web_mujs_tests_mujs_engine_construct (GType object_type) {
	RubricWebMujsTestsMujsEngine * self = NULL;
	self = (RubricWebMujsTestsMujsEngine*) valadate_framework_test_case_construct (object_type);
	return self;
}


RubricWebMujsTestsMujsEngine* rubric_web_mujs_tests_mujs_engine_new (void) {
	return rubric_web_mujs_tests_mujs_engine_construct (RUBRIC_WEB_MUJS_TESTS_TYPE_MUJS_ENGINE);
}


static void rubric_web_mujs_tests_mujs_engine_class_init (RubricWebMujsTestsMujsEngineClass * klass) {
	rubric_web_mujs_tests_mujs_engine_parent_class = g_type_class_peek_parent (klass);
}


static void rubric_web_mujs_tests_mujs_engine_instance_init (RubricWebMujsTestsMujsEngine * self) {
}


GType rubric_web_mujs_tests_mujs_engine_get_type (void) {
	static volatile gsize rubric_web_mujs_tests_mujs_engine_type_id__volatile = 0;
	if (g_once_init_enter (&rubric_web_mujs_tests_mujs_engine_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RubricWebMujsTestsMujsEngineClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rubric_web_mujs_tests_mujs_engine_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RubricWebMujsTestsMujsEngine), 0, (GInstanceInitFunc) rubric_web_mujs_tests_mujs_engine_instance_init, NULL };
		GType rubric_web_mujs_tests_mujs_engine_type_id;
		rubric_web_mujs_tests_mujs_engine_type_id = g_type_register_static (VALADATE_FRAMEWORK_TYPE_TEST_CASE, "RubricWebMujsTestsMujsEngine", &g_define_type_info, 0);
		g_once_init_leave (&rubric_web_mujs_tests_mujs_engine_type_id__volatile, rubric_web_mujs_tests_mujs_engine_type_id);
	}
	return rubric_web_mujs_tests_mujs_engine_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



