/* test-mujs.vapi generated by valac 0.34.7, do not modify. */

[CCode (gir_namespace = "RubricWeb", gir_version = "1.0")]
namespace RubricWeb {
	namespace Mujs {
		namespace Tests {
			[CCode (cheader_filename = "embed.h")]
			public class EmbededObjects : Valadate.Framework.TestCase {
				public EmbededObjects ();
				public void _test_creating_an_instance_of_embedded_builtin_reference_type ();
				public void _test_embedding_of_builtin_reference_type_with_constants ();
				public void _test_embedding_of_builtin_reference_type_with_field ();
				public void _test_embedding_of_builtin_reference_type_with_method ();
				public void _test_embedding_of_builtin_reference_type_with_property ();
				public void _test_embedding_of_builtin_value_type_with_field ();
				public void _test_embedding_of_builtin_value_type_with_property ();
				public void _test_embedding_of_custom_reference_type_with_property ();
				public void _test_embedding_of_instance_of_builtin_reference_type_with_properties ();
				public void _test_embedding_of_instance_of_builtin_value_type_with_properties ();
				public void _test_embedding_of_instance_of_custom_reference_type_with_method ();
				public void _test_embedding_of_instance_of_delegate_with_one_parameter ();
				public void _test_embedding_of_instance_of_delegate_with_two_parameters ();
				public void _test_embedding_of_instance_of_delegate_without_parameters ();
				public void test_creating_an_instance_of_embedded_builtin_value_type ();
				public void test_creating_an_instance_of_embedded_custom_reference_type ();
				public void test_creating_an_instance_of_embedded_custom_value_type ();
				public void test_embedding_of_builtin_value_type_with_method ();
				public void test_embedding_of_custom_reference_type_with_constant ();
				public void test_embedding_of_custom_reference_type_with_field ();
				public void test_embedding_of_custom_reference_type_with_method ();
				public void test_embedding_of_custom_value_type_with_constants ();
				public void test_embedding_of_custom_value_type_with_field ();
				public void test_embedding_of_custom_value_type_with_method ();
				public void test_embedding_of_custom_value_type_with_property ();
				public void test_embedding_of_instance_of_builtin_reference_type_with_method ();
				public void test_embedding_of_instance_of_builtin_value_type_with_methods ();
				public void test_embedding_of_instance_of_custom_reference_type_with_fields ();
				public void test_embedding_of_instance_of_custom_reference_type_with_properties ();
				public void test_embedding_of_instance_of_custom_value_type_with_fields ();
				public void test_embedding_of_instance_of_custom_value_type_with_method ();
				public void test_embedding_of_instance_of_custom_value_type_with_properties ();
			}
		}
	}
}
