/* welcome-view.c generated by valac 0.32.1, the Vala compiler
 * generated from welcome-view.vala, do not modify */

/*
 * Rubric -- a Vala framework for responsive applications
 * Copyright 2016 Chris Daley <chebizarro@gmail.com>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <rubric.h>


#define TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW (tienda_modules_users_welcome_view_get_type ())
#define TIENDA_MODULES_USERS_WELCOME_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeView))
#define TIENDA_MODULES_USERS_WELCOME_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeViewClass))
#define TIENDA_MODULES_USERS_IS_WELCOME_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW))
#define TIENDA_MODULES_USERS_IS_WELCOME_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW))
#define TIENDA_MODULES_USERS_WELCOME_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeViewClass))

typedef struct _TiendaModulesUsersWelcomeView TiendaModulesUsersWelcomeView;
typedef struct _TiendaModulesUsersWelcomeViewClass TiendaModulesUsersWelcomeViewClass;
typedef struct _TiendaModulesUsersWelcomeViewPrivate TiendaModulesUsersWelcomeViewPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TiendaModulesUsersWelcomeView {
	GtkBox parent_instance;
	TiendaModulesUsersWelcomeViewPrivate * priv;
};

struct _TiendaModulesUsersWelcomeViewClass {
	GtkBoxClass parent_class;
};

struct _TiendaModulesUsersWelcomeViewPrivate {
	RubricRegionsRegionManager* _region_manager;
	RubricContainer* _container;
	RubricPresentationViewModel* _view_model;
};


static gpointer tienda_modules_users_welcome_view_parent_class = NULL;
static RubricPresentationViewIface* tienda_modules_users_welcome_view_rubric_presentation_view_parent_iface = NULL;
static GType tienda_modules_users_welcome_view_type_id = 0;

GType tienda_modules_users_welcome_view_get_type (void) G_GNUC_CONST;
GType tienda_modules_users_welcome_view_register_type (GTypeModule * module);
#define TIENDA_MODULES_USERS_WELCOME_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeViewPrivate))
enum  {
	TIENDA_MODULES_USERS_WELCOME_VIEW_DUMMY_PROPERTY,
	TIENDA_MODULES_USERS_WELCOME_VIEW_REGION_MANAGER,
	TIENDA_MODULES_USERS_WELCOME_VIEW_CONTAINER,
	TIENDA_MODULES_USERS_WELCOME_VIEW_VIEW_MODEL
};
TiendaModulesUsersWelcomeView* tienda_modules_users_welcome_view_new (RubricContainer* container);
TiendaModulesUsersWelcomeView* tienda_modules_users_welcome_view_construct (GType object_type, RubricContainer* container);
static void tienda_modules_users_welcome_view_finalize (GObject* obj);
static void _vala_tienda_modules_users_welcome_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tienda_modules_users_welcome_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


TiendaModulesUsersWelcomeView* tienda_modules_users_welcome_view_construct (GType object_type, RubricContainer* container) {
	TiendaModulesUsersWelcomeView * self = NULL;
	RubricContainer* _tmp0_ = NULL;
#line 38 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_return_val_if_fail (container != NULL, NULL);
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = container;
#line 39 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) g_object_new (object_type, "container", _tmp0_, NULL);
#line 38 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return self;
#line 92 "welcome-view.c"
}


TiendaModulesUsersWelcomeView* tienda_modules_users_welcome_view_new (RubricContainer* container) {
#line 38 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return tienda_modules_users_welcome_view_construct (TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, container);
#line 99 "welcome-view.c"
}


static RubricRegionsRegionManager* tienda_modules_users_welcome_view_real_get_region_manager (RubricPresentationView* base) {
	RubricRegionsRegionManager* result;
	TiendaModulesUsersWelcomeView* self;
	RubricRegionsRegionManager* _tmp0_ = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = self->priv->_region_manager;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	result = _tmp0_;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return result;
#line 115 "welcome-view.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return self ? g_object_ref (self) : NULL;
#line 122 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_real_set_region_manager (RubricPresentationView* base, RubricRegionsRegionManager* value) {
	TiendaModulesUsersWelcomeView* self;
	RubricRegionsRegionManager* _tmp0_ = NULL;
	RubricRegionsRegionManager* _tmp1_ = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = value;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_region_manager);
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self->priv->_region_manager = _tmp1_;
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_notify ((GObject *) self, "region-manager");
#line 142 "welcome-view.c"
}


static RubricContainer* tienda_modules_users_welcome_view_real_get_container (RubricPresentationView* base) {
	RubricContainer* result;
	TiendaModulesUsersWelcomeView* self;
	RubricContainer* _tmp0_ = NULL;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = self->priv->_container;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	result = _tmp0_;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return result;
#line 158 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_real_set_container (RubricPresentationView* base, RubricContainer* value) {
	TiendaModulesUsersWelcomeView* self;
	RubricContainer* _tmp0_ = NULL;
	RubricContainer* _tmp1_ = NULL;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = value;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_container);
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self->priv->_container = _tmp1_;
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_notify ((GObject *) self, "container");
#line 178 "welcome-view.c"
}


static RubricPresentationViewModel* tienda_modules_users_welcome_view_real_get_view_model (RubricPresentationView* base) {
	RubricPresentationViewModel* result;
	TiendaModulesUsersWelcomeView* self;
	RubricPresentationViewModel* _tmp0_ = NULL;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = self->priv->_view_model;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	result = _tmp0_;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	return result;
#line 194 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_real_set_view_model (RubricPresentationView* base, RubricPresentationViewModel* value) {
	TiendaModulesUsersWelcomeView* self;
	RubricPresentationViewModel* _tmp0_ = NULL;
	RubricPresentationViewModel* _tmp1_ = NULL;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = (TiendaModulesUsersWelcomeView*) base;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp0_ = value;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_view_model);
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self->priv->_view_model = _tmp1_;
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_notify ((GObject *) self, "view-model");
#line 214 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_class_init (TiendaModulesUsersWelcomeViewClass * klass) {
	gint TiendaModulesUsersWelcomeView_private_offset;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	tienda_modules_users_welcome_view_parent_class = g_type_class_peek_parent (klass);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_type_class_add_private (klass, sizeof (TiendaModulesUsersWelcomeViewPrivate));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_tienda_modules_users_welcome_view_get_property;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_tienda_modules_users_welcome_view_set_property;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	G_OBJECT_CLASS (klass)->finalize = tienda_modules_users_welcome_view_finalize;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TIENDA_MODULES_USERS_WELCOME_VIEW_REGION_MANAGER, g_param_spec_object ("region-manager", "region-manager", "region-manager", RUBRIC_REGIONS_TYPE_REGION_MANAGER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TIENDA_MODULES_USERS_WELCOME_VIEW_CONTAINER, g_param_spec_object ("container", "container", "container", RUBRIC_TYPE_CONTAINER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TIENDA_MODULES_USERS_WELCOME_VIEW_VIEW_MODEL, g_param_spec_object ("view-model", "view-model", "view-model", RUBRIC_PRESENTATION_TYPE_VIEW_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	TiendaModulesUsersWelcomeView_private_offset = g_type_class_get_instance_private_offset (klass);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/tienda/modules/users/views/welcome.ui");
#line 240 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_rubric_presentation_view_interface_init (RubricPresentationViewIface * iface) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	tienda_modules_users_welcome_view_rubric_presentation_view_parent_iface = g_type_interface_peek_parent (iface);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->get_region_manager = tienda_modules_users_welcome_view_real_get_region_manager;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->set_region_manager = tienda_modules_users_welcome_view_real_set_region_manager;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->get_container = tienda_modules_users_welcome_view_real_get_container;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->set_container = tienda_modules_users_welcome_view_real_set_container;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->get_view_model = tienda_modules_users_welcome_view_real_get_view_model;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	iface->set_view_model = tienda_modules_users_welcome_view_real_set_view_model;
#line 259 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_instance_init (TiendaModulesUsersWelcomeView * self) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self->priv = TIENDA_MODULES_USERS_WELCOME_VIEW_GET_PRIVATE (self);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 268 "welcome-view.c"
}


static void tienda_modules_users_welcome_view_finalize (GObject* obj) {
	TiendaModulesUsersWelcomeView * self;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeView);
#line 32 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_region_manager);
#line 34 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_container);
#line 36 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	_g_object_unref0 (self->priv->_view_model);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	G_OBJECT_CLASS (tienda_modules_users_welcome_view_parent_class)->finalize (obj);
#line 284 "welcome-view.c"
}


GType tienda_modules_users_welcome_view_get_type (void) {
	return tienda_modules_users_welcome_view_type_id;
}


GType tienda_modules_users_welcome_view_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (TiendaModulesUsersWelcomeViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tienda_modules_users_welcome_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiendaModulesUsersWelcomeView), 0, (GInstanceInitFunc) tienda_modules_users_welcome_view_instance_init, NULL };
	static const GInterfaceInfo rubric_presentation_view_info = { (GInterfaceInitFunc) tienda_modules_users_welcome_view_rubric_presentation_view_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	tienda_modules_users_welcome_view_type_id = g_type_module_register_type (module, gtk_box_get_type (), "TiendaModulesUsersWelcomeView", &g_define_type_info, 0);
	g_type_module_add_interface (module, tienda_modules_users_welcome_view_type_id, RUBRIC_PRESENTATION_TYPE_VIEW, &rubric_presentation_view_info);
	return tienda_modules_users_welcome_view_type_id;
}


static void _vala_tienda_modules_users_welcome_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiendaModulesUsersWelcomeView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeView);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	switch (property_id) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_REGION_MANAGER:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		g_value_set_object (value, rubric_presentation_view_get_region_manager ((RubricPresentationView*) self));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_CONTAINER:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		g_value_set_object (value, rubric_presentation_view_get_container ((RubricPresentationView*) self));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_VIEW_MODEL:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		g_value_set_object (value, rubric_presentation_view_get_view_model ((RubricPresentationView*) self));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 325 "welcome-view.c"
		default:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 331 "welcome-view.c"
	}
}


static void _vala_tienda_modules_users_welcome_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiendaModulesUsersWelcomeView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TIENDA_MODULES_USERS_TYPE_WELCOME_VIEW, TiendaModulesUsersWelcomeView);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
	switch (property_id) {
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_REGION_MANAGER:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		rubric_presentation_view_set_region_manager ((RubricPresentationView*) self, g_value_get_object (value));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_CONTAINER:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		rubric_presentation_view_set_container ((RubricPresentationView*) self, g_value_get_object (value));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		case TIENDA_MODULES_USERS_WELCOME_VIEW_VIEW_MODEL:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		rubric_presentation_view_set_view_model ((RubricPresentationView*) self, g_value_get_object (value));
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 359 "welcome-view.c"
		default:
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 30 "/home/bizarro/Documents/projects/valadate.org/valarade/valarade/rubric/examples/tienda/modules/users/views/welcome-view.vala"
		break;
#line 365 "welcome-view.c"
	}
}



