/* libmujs.h generated by valac 0.34.7, the Vala compiler, do not modify */


#ifndef __LIBMUJS_H__
#define __LIBMUJS_H__

#include <glib.h>
#include <glib-object.h>
#include <rubric-web.h>

G_BEGIN_DECLS


#define RUBRIC_WEB_MUJS_TYPE_ENGINE (rubric_web_mujs_engine_get_type ())
#define RUBRIC_WEB_MUJS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUBRIC_WEB_MUJS_TYPE_ENGINE, RubricWebMujsEngine))
#define RUBRIC_WEB_MUJS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUBRIC_WEB_MUJS_TYPE_ENGINE, RubricWebMujsEngineClass))
#define RUBRIC_WEB_MUJS_IS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUBRIC_WEB_MUJS_TYPE_ENGINE))
#define RUBRIC_WEB_MUJS_IS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUBRIC_WEB_MUJS_TYPE_ENGINE))
#define RUBRIC_WEB_MUJS_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUBRIC_WEB_MUJS_TYPE_ENGINE, RubricWebMujsEngineClass))

typedef struct _RubricWebMujsEngine RubricWebMujsEngine;
typedef struct _RubricWebMujsEngineClass RubricWebMujsEngineClass;
typedef struct _RubricWebMujsEnginePrivate RubricWebMujsEnginePrivate;

struct _RubricWebMujsEngine {
	GObject parent_instance;
	RubricWebMujsEnginePrivate * priv;
};

struct _RubricWebMujsEngineClass {
	GObjectClass parent_class;
};


GType rubric_web_mujs_engine_get_type (void) G_GNUC_CONST;
RubricWebMujsEngine* rubric_web_mujs_engine_new (void);
RubricWebMujsEngine* rubric_web_mujs_engine_construct (GType object_type);


G_END_DECLS

#endif
