/* mujs-1.0.vapi generated by valac 0.34.7, do not modify. */

[CCode (gir_namespace = "RubricWeb", gir_version = "1.0")]
namespace RubricWeb {
	namespace Mujs {
		[CCode (cheader_filename = "libmujs.h")]
		public class Engine : GLib.Object, RubricWeb.JSEngine {
			public Engine ();
		}
	}
}
