/* test-v8.vapi generated by valac 0.34.7, do not modify. */

[CCode (cprefix = "RubricWebV8", gir_namespace = "RubricWebV8", gir_version = "1.0", lower_case_cprefix = "rubric_web_v8_")]
namespace RubricWebV8 {
	namespace Tests {
		[CCode (cheader_filename = "tests/v8.h")]
		public class V8JSEngine : Valadate.Framework.TestCase {
			public V8JSEngine ();
			public void test_new_engine ();
		}
	}
}
